/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RhcTypes.c
  Source: RhcTypes.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "RhcTypes.h"

static const uint32_t RhcTypes_T_ops [] =
{
  /* T */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (RhcTypes_T, k),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (RhcTypes_T, ks),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (RhcTypes_T, x),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (RhcTypes_T, y),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (RhcTypes_T, s),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */,
  
  /* key: ks */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t RhcTypes_T_keys[2] =
{
  { "k", 11, 0 },
  { "ks", 13, 1 }
};

const dds_topic_descriptor_t RhcTypes_T_desc =
{
  .m_size = sizeof (RhcTypes_T),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 2u,
  .m_typename = "RhcTypes::T",
  .m_keys = RhcTypes_T_keys,
  .m_nops = 6,
  .m_ops = RhcTypes_T_ops,
  .m_meta = ""
};

