/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RhcTypes.h
  Source: RhcTypes.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_RHCTYPES_H
#define DDSC_RHCTYPES_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct RhcTypes_T
{
  int32_t k;
  char * ks;
  int32_t x;
  int32_t y;
  char * s;
} RhcTypes_T;

extern const dds_topic_descriptor_t RhcTypes_T_desc;

#define RhcTypes_T__alloc() \
((RhcTypes_T*) dds_alloc (sizeof (RhcTypes_T)));

#define RhcTypes_T_free(d,o) \
dds_sample_free ((d), &RhcTypes_T_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_RHCTYPES_H */
