/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CdrStreamOptimize.c
  Source: CdrStreamOptimize.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "CdrStreamOptimize.h"

static const uint32_t CdrStreamOptimize_t1_ops [] =
{
  /* t1 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t1, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t1_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t1",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = CdrStreamOptimize_t1_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t1_a_ops [] =
{
  /* t1_a */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t1_a, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t1_a_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t1_a),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t1_a",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = CdrStreamOptimize_t1_a_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t1_m_ops [] =
{
  /* t1_m */
  DDS_OP_PLC,
  DDS_OP_PLM | 3, 0u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t1_m, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t1_m_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t1_m),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t1_m",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = CdrStreamOptimize_t1_m_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t2_ops [] =
{
  /* t2 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_t2, f1),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t2, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t2_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t2),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t2",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = CdrStreamOptimize_t2_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t3_ops [] =
{
  /* t3 */
  DDS_OP_ADR | DDS_OP_FLAG_EXT | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_t3, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t3_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t3),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t3",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = CdrStreamOptimize_t3_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t4_ops [] =
{
  /* t4 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4, f1), (3u << 16u) + 4u /* n1 */,
  DDS_OP_RTS,

  /* n1 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n1, f1),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n1, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t4_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t4),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t4",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = CdrStreamOptimize_t4_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t4_1_ops [] =
{
  /* t4_1 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_1, f1), (3u << 16u) + 7u /* n1 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_1, f2), (3u << 16u) + 4u /* n1 */,
  DDS_OP_RTS,

  /* n1 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n1, f1),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n1, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t4_1_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t4_1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t4_1",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = CdrStreamOptimize_t4_1_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t4_2_ops [] =
{
  /* t4_2 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_2, f1), (3u << 16u) + 7u /* t4_1 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_2, f2), (3u << 16u) + 4u /* t4_1 */,
  DDS_OP_RTS,

  /* t4_1 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_1, f1), (3u << 16u) + 7u /* n1 */,
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t4_1, f2), (3u << 16u) + 4u /* n1 */,
  DDS_OP_RTS,

  /* n1 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n1, f1),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n1, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t4_2_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t4_2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t4_2",
  .m_keys = NULL,
  .m_nops = 9,
  .m_ops = CdrStreamOptimize_t4_2_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t5_ops [] =
{
  /* t5 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t5, f1), (3u << 16u) + 4u /* n2 */,
  DDS_OP_RTS,

  /* n2 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n2, f1),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n2, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t5_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t5),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t5",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = CdrStreamOptimize_t5_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t6_ops [] =
{
  /* t6 */
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (CdrStreamOptimize_t6, f1), 3u, (5u << 16u) + 6u /* n2 */, sizeof (CdrStreamOptimize_n2),
  DDS_OP_RTS,

  /* n2 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n2, f1),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n2, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t6_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t6),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t6",
  .m_keys = NULL,
  .m_nops = 5,
  .m_ops = CdrStreamOptimize_t6_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t7_ops [] =
{
  /* t7 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_t7, f1),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CdrStreamOptimize_t7, f2),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_t7, f3),
  DDS_OP_ADR | DDS_OP_TYPE_2BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t7, f5),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t7, f6),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t7_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t7),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t7",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = CdrStreamOptimize_t7_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t8_ops [] =
{
  /* t8 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_t8, f1),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t8, f2), (3u << 16u) + 6u /* n3 */,
  DDS_OP_ADR | DDS_OP_TYPE_2BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t8, f3),
  DDS_OP_RTS,

  /* n3 */
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CdrStreamOptimize_n3, f1),
  DDS_OP_ADR | DDS_OP_TYPE_2BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n3, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t8_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t8),
  .m_align = 2u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t8",
  .m_keys = NULL,
  .m_nops = 7,
  .m_ops = CdrStreamOptimize_t8_ops,
  .m_meta = ""
};

static const uint32_t CdrStreamOptimize_t9_ops [] =
{
  /* t9 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_t9, f1),
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (CdrStreamOptimize_t9, f2), (3u << 16u) + 4u /* n4 */,
  DDS_OP_RTS,

  /* n4 */
  DDS_OP_DLC,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CdrStreamOptimize_n4, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t CdrStreamOptimize_t9_desc =
{
  .m_size = sizeof (CdrStreamOptimize_t9),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "CdrStreamOptimize::t9",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = CdrStreamOptimize_t9_ops,
  .m_meta = ""
};

