/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: CdrStreamOptimize.h
  Source: CdrStreamOptimize.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_CDRSTREAMOPTIMIZE_H
#define DDSC_CDRSTREAMOPTIMIZE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CdrStreamOptimize_t1
{
  int32_t f1;
} CdrStreamOptimize_t1;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_desc;

#define CdrStreamOptimize_t1__alloc() \
((CdrStreamOptimize_t1*) dds_alloc (sizeof (CdrStreamOptimize_t1)));

#define CdrStreamOptimize_t1_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_desc, (o))

typedef struct CdrStreamOptimize_t1_a
{
  int32_t f1;
} CdrStreamOptimize_t1_a;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_a_desc;

#define CdrStreamOptimize_t1_a__alloc() \
((CdrStreamOptimize_t1_a*) dds_alloc (sizeof (CdrStreamOptimize_t1_a)));

#define CdrStreamOptimize_t1_a_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_a_desc, (o))

typedef struct CdrStreamOptimize_t1_m
{
  int32_t f1;
} CdrStreamOptimize_t1_m;

extern const dds_topic_descriptor_t CdrStreamOptimize_t1_m_desc;

#define CdrStreamOptimize_t1_m__alloc() \
((CdrStreamOptimize_t1_m*) dds_alloc (sizeof (CdrStreamOptimize_t1_m)));

#define CdrStreamOptimize_t1_m_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t1_m_desc, (o))

typedef struct CdrStreamOptimize_t2
{
  uint8_t f1;
  int64_t f2;
} CdrStreamOptimize_t2;

extern const dds_topic_descriptor_t CdrStreamOptimize_t2_desc;

#define CdrStreamOptimize_t2__alloc() \
((CdrStreamOptimize_t2*) dds_alloc (sizeof (CdrStreamOptimize_t2)));

#define CdrStreamOptimize_t2_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t2_desc, (o))

typedef struct CdrStreamOptimize_t3
{
  uint8_t * f1;
} CdrStreamOptimize_t3;

extern const dds_topic_descriptor_t CdrStreamOptimize_t3_desc;

#define CdrStreamOptimize_t3__alloc() \
((CdrStreamOptimize_t3*) dds_alloc (sizeof (CdrStreamOptimize_t3)));

#define CdrStreamOptimize_t3_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t3_desc, (o))

typedef struct CdrStreamOptimize_n1
{
  int32_t f1;
  uint8_t f2;
} CdrStreamOptimize_n1;

typedef struct CdrStreamOptimize_t4
{
  struct CdrStreamOptimize_n1 f1;
} CdrStreamOptimize_t4;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4_desc;

#define CdrStreamOptimize_t4__alloc() \
((CdrStreamOptimize_t4*) dds_alloc (sizeof (CdrStreamOptimize_t4)));

#define CdrStreamOptimize_t4_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4_desc, (o))

typedef struct CdrStreamOptimize_t4_1
{
  struct CdrStreamOptimize_n1 f1;
  struct CdrStreamOptimize_n1 f2;
} CdrStreamOptimize_t4_1;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4_1_desc;

#define CdrStreamOptimize_t4_1__alloc() \
((CdrStreamOptimize_t4_1*) dds_alloc (sizeof (CdrStreamOptimize_t4_1)));

#define CdrStreamOptimize_t4_1_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4_1_desc, (o))

typedef struct CdrStreamOptimize_t4_2
{
  struct CdrStreamOptimize_t4_1 f1;
  struct CdrStreamOptimize_t4_1 f2;
} CdrStreamOptimize_t4_2;

extern const dds_topic_descriptor_t CdrStreamOptimize_t4_2_desc;

#define CdrStreamOptimize_t4_2__alloc() \
((CdrStreamOptimize_t4_2*) dds_alloc (sizeof (CdrStreamOptimize_t4_2)));

#define CdrStreamOptimize_t4_2_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t4_2_desc, (o))

typedef struct CdrStreamOptimize_n2
{
  uint8_t f1;
  int64_t f2;
} CdrStreamOptimize_n2;

typedef struct CdrStreamOptimize_t5
{
  struct CdrStreamOptimize_n2 f1;
} CdrStreamOptimize_t5;

extern const dds_topic_descriptor_t CdrStreamOptimize_t5_desc;

#define CdrStreamOptimize_t5__alloc() \
((CdrStreamOptimize_t5*) dds_alloc (sizeof (CdrStreamOptimize_t5)));

#define CdrStreamOptimize_t5_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t5_desc, (o))

typedef struct CdrStreamOptimize_t6
{
  struct CdrStreamOptimize_n2 f1[3];
} CdrStreamOptimize_t6;

extern const dds_topic_descriptor_t CdrStreamOptimize_t6_desc;

#define CdrStreamOptimize_t6__alloc() \
((CdrStreamOptimize_t6*) dds_alloc (sizeof (CdrStreamOptimize_t6)));

#define CdrStreamOptimize_t6_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t6_desc, (o))

typedef enum CdrStreamOptimize_en1
{
  CdrStreamOptimize_E1,
  CdrStreamOptimize_E2
} CdrStreamOptimize_en1;

#define CdrStreamOptimize_en1__alloc() \
((CdrStreamOptimize_en1*) dds_alloc (sizeof (CdrStreamOptimize_en1)));

typedef struct CdrStreamOptimize_t7
{
  bool f1;
  CdrStreamOptimize_en1 f2;
  uint8_t f3;
  int16_t f5;
  int32_t f6;
} CdrStreamOptimize_t7;

extern const dds_topic_descriptor_t CdrStreamOptimize_t7_desc;

#define CdrStreamOptimize_t7__alloc() \
((CdrStreamOptimize_t7*) dds_alloc (sizeof (CdrStreamOptimize_t7)));

#define CdrStreamOptimize_t7_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t7_desc, (o))

typedef struct CdrStreamOptimize_n3
{
  uint8_t f1;
  int16_t f2;
} CdrStreamOptimize_n3;

typedef struct CdrStreamOptimize_t8
{
  uint8_t f1;
  struct CdrStreamOptimize_n3 f2;
  int16_t f3;
} CdrStreamOptimize_t8;

extern const dds_topic_descriptor_t CdrStreamOptimize_t8_desc;

#define CdrStreamOptimize_t8__alloc() \
((CdrStreamOptimize_t8*) dds_alloc (sizeof (CdrStreamOptimize_t8)));

#define CdrStreamOptimize_t8_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t8_desc, (o))

typedef struct CdrStreamOptimize_n4
{
  int32_t f1;
} CdrStreamOptimize_n4;

typedef struct CdrStreamOptimize_t9
{
  int32_t f1;
  struct CdrStreamOptimize_n4 f2;
} CdrStreamOptimize_t9;

extern const dds_topic_descriptor_t CdrStreamOptimize_t9_desc;

#define CdrStreamOptimize_t9__alloc() \
((CdrStreamOptimize_t9*) dds_alloc (sizeof (CdrStreamOptimize_t9)));

#define CdrStreamOptimize_t9_free(d,o) \
dds_sample_free ((d), &CdrStreamOptimize_t9_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_CDRSTREAMOPTIMIZE_H */
