/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: InstanceHandleTypes.c
  Source: InstanceHandleTypes.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "InstanceHandleTypes.h"

static const uint32_t InstanceHandleTypes_A_ops [] =
{
  /* A */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (InstanceHandleTypes_A, k),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (InstanceHandleTypes_A, v),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t InstanceHandleTypes_A_keys[1] =
{
  { "k", 5, 0 }
};

const dds_topic_descriptor_t InstanceHandleTypes_A_desc =
{
  .m_size = sizeof (InstanceHandleTypes_A),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "InstanceHandleTypes::A",
  .m_keys = InstanceHandleTypes_A_keys,
  .m_nops = 3,
  .m_ops = InstanceHandleTypes_A_ops,
  .m_meta = ""
};

static const uint32_t InstanceHandleTypes_C_ops [] =
{
  /* C */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (InstanceHandleTypes_C, k),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (InstanceHandleTypes_C, v),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t InstanceHandleTypes_C_keys[1] =
{
  { "k", 5, 0 }
};

const dds_topic_descriptor_t InstanceHandleTypes_C_desc =
{
  .m_size = sizeof (InstanceHandleTypes_C),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "InstanceHandleTypes::C",
  .m_keys = InstanceHandleTypes_C_keys,
  .m_nops = 3,
  .m_ops = InstanceHandleTypes_C_ops,
  .m_meta = ""
};

static const uint32_t InstanceHandleTypes_MD5_ops [] =
{
  /* MD5 */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (InstanceHandleTypes_MD5, k), 128u,
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t InstanceHandleTypes_MD5_keys[1] =
{
  { "k", 4, 0 }
};

const dds_topic_descriptor_t InstanceHandleTypes_MD5_desc =
{
  .m_size = sizeof (InstanceHandleTypes_MD5),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "InstanceHandleTypes::MD5",
  .m_keys = InstanceHandleTypes_MD5_keys,
  .m_nops = 2,
  .m_ops = InstanceHandleTypes_MD5_ops,
  .m_meta = ""
};

