/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RWData.c
  Source: RWData.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "RWData.h"

static const uint32_t RWData_Msg_ops [] =
{
  /* Msg */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (RWData_Msg, k),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t RWData_Msg_keys[1] =
{
  { "k", 3, 0 }
};

const dds_topic_descriptor_t RWData_Msg_desc =
{
  .m_size = sizeof (RWData_Msg),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "RWData::Msg",
  .m_keys = RWData_Msg_keys,
  .m_nops = 2,
  .m_ops = RWData_Msg_ops,
  .m_meta = ""
};

