/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Space.h
  Source: Space.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_SPACE_H
#define DDSC_SPACE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Space_Type1
{
  int32_t long_1;
  int32_t long_2;
  int32_t long_3;
} Space_Type1;

extern const dds_topic_descriptor_t Space_Type1_desc;

#define Space_Type1__alloc() \
((Space_Type1*) dds_alloc (sizeof (Space_Type1)));

#define Space_Type1_free(d,o) \
dds_sample_free ((d), &Space_Type1_desc, (o))

typedef struct Space_Type2
{
  int32_t long_1;
  int32_t long_2;
  int32_t long_3;
} Space_Type2;

extern const dds_topic_descriptor_t Space_Type2_desc;

#define Space_Type2__alloc() \
((Space_Type2*) dds_alloc (sizeof (Space_Type2)));

#define Space_Type2_free(d,o) \
dds_sample_free ((d), &Space_Type2_desc, (o))

typedef struct Space_Type3
{
  int32_t long_1;
  int32_t long_2;
  int32_t long_3;
} Space_Type3;

extern const dds_topic_descriptor_t Space_Type3_desc;

#define Space_Type3__alloc() \
((Space_Type3*) dds_alloc (sizeof (Space_Type3)));

#define Space_Type3_free(d,o) \
dds_sample_free ((d), &Space_Type3_desc, (o))

typedef struct Space_simpletypes
{
  int32_t l;
  int64_t ll;
  uint16_t us;
  uint32_t ul;
  uint64_t ull;
  float f;
  double d;
  char c;
  bool b;
  uint8_t o;
  char * s;
} Space_simpletypes;

extern const dds_topic_descriptor_t Space_simpletypes_desc;

#define Space_simpletypes__alloc() \
((Space_simpletypes*) dds_alloc (sizeof (Space_simpletypes)));

#define Space_simpletypes_free(d,o) \
dds_sample_free ((d), &Space_simpletypes_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SPACE_H */
