/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: SecurityCoreTests.c
  Source: SecurityCoreTests.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "SecurityCoreTests.h"

static const uint32_t SecurityCoreTests_Type1_ops [] =
{
  /* Type1 */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (SecurityCoreTests_Type1, id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (SecurityCoreTests_Type1, value),
  DDS_OP_RTS,
  
  /* key: id */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t SecurityCoreTests_Type1_keys[1] =
{
  { "id", 5, 0 }
};

const dds_topic_descriptor_t SecurityCoreTests_Type1_desc =
{
  .m_size = sizeof (SecurityCoreTests_Type1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "SecurityCoreTests::Type1",
  .m_keys = SecurityCoreTests_Type1_keys,
  .m_nops = 3,
  .m_ops = SecurityCoreTests_Type1_ops,
  .m_meta = ""
};

static const uint32_t SecurityCoreTests_Type2_ops [] =
{
  /* Type2 */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (SecurityCoreTests_Type2, id),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (SecurityCoreTests_Type2, text),
  DDS_OP_RTS,
  
  /* key: id */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t SecurityCoreTests_Type2_keys[1] =
{
  { "id", 5, 0 }
};

const dds_topic_descriptor_t SecurityCoreTests_Type2_desc =
{
  .m_size = sizeof (SecurityCoreTests_Type2),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2,
  .m_nkeys = 1u,
  .m_typename = "SecurityCoreTests::Type2",
  .m_keys = SecurityCoreTests_Type2_keys,
  .m_nops = 3,
  .m_ops = SecurityCoreTests_Type2_ops,
  .m_meta = ""
};

