/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: InitSampleDelivData.c
  Source: InitSampleDelivData.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "InitSampleDelivData.h"

static const uint32_t Msg_ops [] =
{
  /* Msg */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Msg, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Msg, seq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Msg, tldepth),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Msg, final_seq),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Msg, seq_at_match), 2u,
  DDS_OP_RTS,
  
  /* key: keyval */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t Msg_keys[1] =
{
  { "keyval", 12, 0 }
};

const dds_topic_descriptor_t Msg_desc =
{
  .m_size = sizeof (Msg),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "Msg",
  .m_keys = Msg_keys,
  .m_nops = 6,
  .m_ops = Msg_ops,
  .m_meta = ""
};

