/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: InitSampleDelivData.h
  Source: InitSampleDelivData.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#ifndef DDSC_INITSAMPLEDELIVDATA_H
#define DDSC_INITSAMPLEDELIVDATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Msg
{
  int32_t keyval;
  int32_t seq;
  int32_t tldepth;
  int32_t final_seq;
  int32_t seq_at_match[2];
} Msg;

extern const dds_topic_descriptor_t Msg_desc;

#define Msg__alloc() \
((Msg*) dds_alloc (sizeof (Msg)));

#define Msg_free(d,o) \
dds_sample_free ((d), &Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_INITSAMPLEDELIVDATA_H */
