/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ddsperf_types.c
  Source: ddsperf_types.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "ddsperf_types.h"

static const uint32_t OneULong_ops [] =
{
  /* OneULong */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (OneULong, seq),
  DDS_OP_RTS
};

const dds_topic_descriptor_t OneULong_desc =
{
  .m_size = sizeof (OneULong),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "OneULong",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = OneULong_ops,
  .m_meta = ""
};

static const uint32_t Unkeyed16_ops [] =
{
  /* Unkeyed16 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Unkeyed16, seq),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Unkeyed16, baggage), 12u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unkeyed16_desc =
{
  .m_size = sizeof (Unkeyed16),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unkeyed16",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = Unkeyed16_ops,
  .m_meta = ""
};

static const uint32_t Unkeyed1024_ops [] =
{
  /* Unkeyed1024 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Unkeyed1024, seq),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Unkeyed1024, baggage), 1020u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unkeyed1024_desc =
{
  .m_size = sizeof (Unkeyed1024),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Unkeyed1024",
  .m_keys = NULL,
  .m_nops = 3,
  .m_ops = Unkeyed1024_ops,
  .m_meta = ""
};

static const uint32_t Keyed32_ops [] =
{
  /* Keyed32 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Keyed32, seq),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (Keyed32, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Keyed32, baggage), 24u,
  DDS_OP_RTS,
  
  /* key: keyval */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t Keyed32_keys[1] =
{
  { "keyval", 8, 0 }
};

const dds_topic_descriptor_t Keyed32_desc =
{
  .m_size = sizeof (Keyed32),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "Keyed32",
  .m_keys = Keyed32_keys,
  .m_nops = 4,
  .m_ops = Keyed32_ops,
  .m_meta = ""
};

static const uint32_t Keyed256_ops [] =
{
  /* Keyed256 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Keyed256, seq),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (Keyed256, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Keyed256, baggage), 248u,
  DDS_OP_RTS,
  
  /* key: keyval */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t Keyed256_keys[1] =
{
  { "keyval", 8, 0 }
};

const dds_topic_descriptor_t Keyed256_desc =
{
  .m_size = sizeof (Keyed256),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "Keyed256",
  .m_keys = Keyed256_keys,
  .m_nops = 4,
  .m_ops = Keyed256_ops,
  .m_meta = ""
};

static const uint32_t KeyedSeq_ops [] =
{
  /* KeyedSeq */
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (KeyedSeq, seq),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (KeyedSeq, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (KeyedSeq, baggage),
  DDS_OP_RTS,
  
  /* key: keyval */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t KeyedSeq_keys[1] =
{
  { "keyval", 7, 0 }
};

const dds_topic_descriptor_t KeyedSeq_desc =
{
  .m_size = sizeof (KeyedSeq),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2,
  .m_nkeys = 1u,
  .m_typename = "KeyedSeq",
  .m_keys = KeyedSeq_keys,
  .m_nops = 4,
  .m_ops = KeyedSeq_ops,
  .m_meta = ""
};

static const uint32_t CPUStats_ops [] =
{
  /* CPUStats */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (CPUStats, hostname),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (CPUStats, pid),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (CPUStats, maxrss),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStats, vcsw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStats, ivcsw),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (CPUStats, some_above),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (CPUStats, cpu), sizeof (CPUStatThread), (4u << 16u) + 5u /* CPUStatThread */,
  DDS_OP_RTS,

  /* CPUStatThread */
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (CPUStatThread, name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CPUStatThread, u_pct),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (CPUStatThread, s_pct),
  DDS_OP_RTS,
  
  /* key: hostname */
  DDS_OP_KOF | 1, 0u /* order: 0 */,
  
  /* key: pid */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t CPUStats_keys[2] =
{
  { "hostname", 24, 0 },
  { "pid", 26, 1 }
};

const dds_topic_descriptor_t CPUStats_desc =
{
  .m_size = sizeof (CPUStats),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 2u,
  .m_typename = "CPUStats",
  .m_keys = CPUStats_keys,
  .m_nops = 12,
  .m_ops = CPUStats_ops,
  .m_meta = ""
};

