# CMake generated Testfile for 
# Source directory: /home/pi/Documents/cyclonedds/src/tools/idlc/tests
# Build directory: /home/pi/Documents/cyclonedds/build/src/tools/idlc/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CUnit_idlc_descriptor_keys_nested "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "keys_nested")
set_tests_properties(CUnit_idlc_descriptor_keys_nested PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
add_test(CUnit_idlc_descriptor_default_extensibility "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "default_extensibility")
set_tests_properties(CUnit_idlc_descriptor_default_extensibility PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
add_test(CUnit_idlc_descriptor_key_size "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "key_size")
set_tests_properties(CUnit_idlc_descriptor_key_size PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
add_test(CUnit_idlc_descriptor_key_valid_types "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "key_valid_types")
set_tests_properties(CUnit_idlc_descriptor_key_valid_types PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
add_test(CUnit_idlc_descriptor_keys_inheritance "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "keys_inheritance")
set_tests_properties(CUnit_idlc_descriptor_keys_inheritance PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
add_test(CUnit_idlc_descriptor_no_optimize "/home/pi/Documents/cyclonedds/build/bin/cunit_idlc" "-s" "idlc_descriptor" "-t" "no_optimize")
set_tests_properties(CUnit_idlc_descriptor_no_optimize PROPERTIES  DISABLED "FALSE" ENVIRONMENT "LD_LIBRARY_PATH=/home/pi/Documents/cyclonedds/build/lib::" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/pi/Documents/cyclonedds/cmake/Modules/CUnit.cmake;301;add_test;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;28;add_cunit_executable;/home/pi/Documents/cyclonedds/src/tools/idlc/tests/CMakeLists.txt;0;")
