/*
 * Copyright(c) 2006 to 2018 ADLINK Technology Limited and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
 * v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define EX_USAGE (64)
#define EX_SOFTWARE (70)

#include <CUnit/Basic.h>
#include <CUnit/Automated.h>
#include "CUnit/Test.h"

static struct {
    bool print_help;
    bool automated;
    bool junit;
    const char *results;
    CU_BasicRunMode mode;
    CU_ErrorAction error_action;
    const char *suite;
    const char *test;
} opts = {
    false,
    false,
    false,
    NULL,
    CU_BRM_NORMAL,
    CUEA_IGNORE,
    "*",
    "*"
};

static int patmatch(const char *pat, const char *str)
{
    while (*pat) {
        if (*pat == '?') {
            /* any character will do */
            if (*str++ == 0) {
                return 0;
            }
            pat++;
        } else if (*pat == '*') {
            /* collapse a sequence of wildcards, requiring as many
               characters in str as there are ?s in the sequence */
            while (*pat == '*' || *pat == '?') {
                if (*pat == '?' && *str++ == 0) {
                    return 0;
                }
                pat++;
            }
            /* try matching on all positions where str matches pat */
            while (*str) {
                if (*str == *pat && patmatch(pat+1, str+1)) {
                    return 1;
                }
                str++;
            }
            return *pat == 0;
        } else {
            /* only an exact match */
            if (*str++ != *pat++) {
                return 0;
            }
        }
    }

    return *str == 0;
}

static void usage(const char *name)
{
    fprintf(stderr, "Usage: %s OPTIONS\n", name);
    fprintf(stderr, "Try '%s -h' for more information\n", name);
}

static void help(const char *name)
{
    printf("Usage: %s [OPTIONS]\n", name);
    printf("\n");
    printf("Possible options:\n");
    printf("  -a           run in automated mode\n");
    printf("  -f           fail fast\n");
    printf("  -h           display this help and exit\n");
    printf("  -j           junit format results \n");
    printf("  -r FILENAME  results file for automated run\n");
    printf("  -s PATTERN   run only tests in suites matching pattern\n");
    printf("  -t PATTERN   run only test matching pattern\n");
    printf("\n");
    printf("Exit codes:\n");
    printf("  %-2d  Successful termination\n", EXIT_SUCCESS);
    printf("  %-2d  One or more failing test cases\n", EXIT_FAILURE);
    printf("  %-2d  Command line usage error\n", EX_USAGE);
    printf("  %-2d  Internal software error\n", EX_SOFTWARE);
}

static int parse_options(int argc, char *argv[])
{
    int err = 0;

    for (int i = 1; err == 0 && i < argc; i++) {
        switch ((argv[i][0] == '-') ? argv[i][1] : 0) {
            case 'a':
                opts.automated = true;
                break;
            case 'f':
                opts.error_action = CUEA_FAIL;
                break;
            case 'h':
                opts.print_help = true;
                break;
            case 'j':
                opts.junit = true;
                break;
            case 'r':
                if((i+1) < argc){
                    opts.results = argv[++i];
                    break;
                }
                /* FALLS THROUGH */
            case 's':
                if ((i+1) < argc) {
                    opts.suite = argv[++i];
                    break;
                }
                /* FALLS THROUGH */
            case 't':
                if ((i+1) < argc) {
                    opts.test = argv[++i];
                    break;
                }
                /* FALLS THROUGH */
            default:
                err = 1;
                break;
        }
    }

    return err;
}

static void
add_suite(
    const char *suite,
    CU_InitializeFunc pInitFunc,
    CU_CleanupFunc pCleanFunc)
{
    CU_pSuite pSuite;

    pSuite = CU_get_suite(suite);
    if (pSuite == NULL) {
        pSuite = CU_add_suite(suite, pInitFunc, pCleanFunc);
        CU_set_suite_active(pSuite, patmatch(opts.suite, suite));
    }
}

#define ADD_SUITE(suite, init, clean) \
  add_suite(#suite, init, clean)

static void
add_test(
    const char *suite,
    const char *test,
    CU_TestFunc pTestFunc,
    bool enable)
{
    CU_pSuite pSuite;
    CU_pTest pTest;

    pSuite = CU_get_suite(suite);
    pTest = CU_add_test(pSuite, test, pTestFunc);
    CU_set_test_active(pTest, enable && patmatch(opts.test, test));
}

#define ADD_TEST(suite, test, enable) \
  add_test(#suite, #test, CU_TestProxyName(suite, test), enable)

/* CMake will expand the macro below to declare generated functions. */

CU_TestDecl(ddsc_basic, test);
CU_TestDecl(ddsc_builtin_topics, availability_builtin_topics);
CU_TestDecl(ddsc_builtin_topics, read_publication_data);
CU_TestDecl(ddsc_builtin_topics, read_subscription_data);
CU_TestDecl(ddsc_builtin_topics, read_participant_data);
CU_TestDecl(ddsc_builtin_topics, read_topic_data);
CU_TestDecl(ddsc_builtin_topics, same_subscriber);
CU_TestDecl(ddsc_builtin_topics, builtin_qos);
CU_TestDecl(ddsc_builtin_topics, read_nothing);
CU_TestDecl(ddsc_builtin_topics, get_topic);
CU_TestDecl(ddsc_builtin_topics, get_name);
CU_TestDecl(ddsc_builtin_topics, get_type_name);
CU_TestDecl(ddsc_builtin_topics, get_children);
CU_TestDecl(ddsc_builtin_topics, cant_use_real_topic);
CU_TestDecl(ddsc_builtin_topics, get_qos);
CU_TestDecl(ddsc_cdr, basic);
CU_TestDecl(ddsc_cdr_sertopic, basic);
CU_TestDecl(ddsc_cdr, forward);
CU_TestDecl(ddsc_cdr_sertopic, forward);
CU_TestDecl(ddsc_cdr, invalid_data);
CU_TestDecl(ddsc_cdr_sertopic, invalid_data);
CU_TestDecl(ddsc_cdr, timeout);
CU_TestDecl(ddsc_cdr_sertopic, timeout);
CU_TestDecl(ddsc_config, simple_udp);
CU_TestDecl(ddsc_config, user_config);
CU_TestDecl(ddsc_config, ignoredpartition);
CU_TestDecl(ddsc_security_config, empty);
CU_TestDecl(ddsc_security_qos, empty);
CU_TestDecl(ddsc_config, invalid_envvar);
CU_TestDecl(ddsc_config, too_deep_nesting);
CU_TestDecl(ddsc_config, multiple_domains);
CU_TestDecl(ddsc_data_avail_stress, local);
CU_TestDecl(ddsc_data_avail_stress, remote);
CU_TestDecl(ddsc_discstress, create_writer);
CU_TestDecl(ddsc_writedispose, deleted);
CU_TestDecl(ddsc_writedispose, null);
CU_TestDecl(ddsc_writedispose, disposing_old_instance);
CU_TestDecl(ddsc_writedispose, disposing_new_instance);
CU_TestDecl(ddsc_writedispose, timeout);
CU_TestDecl(ddsc_writedispose_ts, deleted);
CU_TestDecl(ddsc_writedispose_ts, null);
CU_TestDecl(ddsc_writedispose_ts, timeout);
CU_TestDecl(ddsc_writedispose_ts, disposing_old_instance);
CU_TestDecl(ddsc_writedispose_ts, disposing_new_instance);
CU_TestDecl(ddsc_writedispose_ts, disposing_past_sample);
CU_TestDecl(ddsc_dispose, deleted);
CU_TestDecl(ddsc_dispose, null);
CU_TestDecl(ddsc_dispose, timeout);
CU_TestDecl(ddsc_dispose, disposing_old_instance);
CU_TestDecl(ddsc_dispose, disposing_new_instance);
CU_TestDecl(ddsc_dispose_ts, deleted);
CU_TestDecl(ddsc_dispose_ts, null);
CU_TestDecl(ddsc_dispose_ts, timeout);
CU_TestDecl(ddsc_dispose_ts, disposing_old_instance);
CU_TestDecl(ddsc_dispose_ts, disposing_new_instance);
CU_TestDecl(ddsc_dispose_ts, disposing_past_sample);
CU_TestDecl(ddsc_dispose_ih, deleted);
CU_TestDecl(ddsc_dispose_ih, disposing_old_instance);
CU_TestDecl(ddsc_dispose_ih_ts, deleted);
CU_TestDecl(ddsc_dispose_ih_ts, disposing_old_instance);
CU_TestDecl(ddsc_dispose_ih_ts, disposing_past_sample);
CU_TestDecl(ddsc_writedispose, invalid_writers);
CU_TestDecl(ddsc_writedispose, non_writers);
CU_TestDecl(ddsc_writedispose_ts, invalid_writers);
CU_TestDecl(ddsc_writedispose_ts, non_writers);
CU_TestDecl(ddsc_dispose, invalid_writers);
CU_TestDecl(ddsc_dispose, non_writers);
CU_TestDecl(ddsc_dispose_ts, invalid_writers);
CU_TestDecl(ddsc_dispose_ts, non_writers);
CU_TestDecl(ddsc_dispose_ih, invalid_handles);
CU_TestDecl(ddsc_dispose_ih, invalid_writers);
CU_TestDecl(ddsc_dispose_ih, non_writers);
CU_TestDecl(ddsc_dispose_ih_ts, invalid_handles);
CU_TestDecl(ddsc_dispose_ih_ts, invalid_writers);
CU_TestDecl(ddsc_dispose_ih_ts, non_writers);
CU_TestDecl(ddsc_domain, get_domainid);
CU_TestDecl(ddsc_domain, delete_domain0);
CU_TestDecl(ddsc_domain, delete_domainM);
CU_TestDecl(ddsc_domain, delete_cyclonedds);
CU_TestDecl(ddsc_domain_create, valid);
CU_TestDecl(ddsc_domain_create, mismatch);
CU_TestDecl(ddsc_domain_create, empty);
CU_TestDecl(ddsc_domain_create, null);
CU_TestDecl(ddsc_domain_create, after_domain);
CU_TestDecl(ddsc_domain_create, after_participant);
CU_TestDecl(ddsc_domain_create, diff);
CU_TestDecl(ddsc_domain_create, domain_default);
CU_TestDecl(ddsc_domain_create, invalid_xml);
CU_TestDecl(ddsc_domain_create, raw_config);
CU_TestDecl(ddsc_domain, torture_implicit);
CU_TestDecl(ddsc_domain, torture_explicit);
CU_TestDecl(ddsc_entity, create);
CU_TestDecl(ddsc_entity, enable);
CU_TestDecl(ddsc_entity, qos);
CU_TestDecl(ddsc_entity, listener);
CU_TestDecl(ddsc_entity, status);
CU_TestDecl(ddsc_entity, guid);
CU_TestDecl(ddsc_entity, instance_handle);
CU_TestDecl(ddsc_entity, get_entities);
CU_TestDecl(ddsc_entity, get_domainid);
CU_TestDecl(ddsc_entity, delete);
CU_TestDecl(ddsc_entity_delete, recursive);
CU_TestDecl(ddsc_entity_delete, recursive_with_deleted_topic);
CU_TestDecl(ddsc_entity_get_parent, reader);
CU_TestDecl(ddsc_entity_get_parent, writer);
CU_TestDecl(ddsc_entity_get_parent, participant);
CU_TestDecl(ddsc_entity_get_children, null);
CU_TestDecl(ddsc_entity_get_children, invalid_size);
CU_TestDecl(ddsc_entity_get_children, too_small);
CU_TestDecl(ddsc_entity_get_children, participant);
CU_TestDecl(ddsc_entity_get_children, topic);
CU_TestDecl(ddsc_entity_get_children, publisher);
CU_TestDecl(ddsc_entity_get_children, subscriber);
CU_TestDecl(ddsc_entity_get_children, writer);
CU_TestDecl(ddsc_entity_get_children, reader);
CU_TestDecl(ddsc_entity_get_publisher, writer);
CU_TestDecl(ddsc_entity_get_publisher, deleted_writer);
CU_TestDecl(ddsc_entity_implicit_publisher, deleted);
CU_TestDecl(ddsc_entity_implicit_publisher, invalid_topic);
CU_TestDecl(ddsc_entity_implicit_subscriber, deleted);
CU_TestDecl(ddsc_entity_explicit_subscriber, invalid_topic);
CU_TestDecl(ddsc_entity_get_children, implicit_publisher);
CU_TestDecl(ddsc_entity_get_children, implicit_subscriber);
CU_TestDecl(ddsc_entity_get_parent, implicit_publisher);
CU_TestDecl(ddsc_entity_get_parent, implicit_subscriber);
CU_TestDecl(ddsc_entity_implicit, delete_publisher);
CU_TestDecl(ddsc_entity_implicit, delete_subscriber);
CU_TestDecl(ddsc_entity_get_participant, valid_entities);
CU_TestDecl(ddsc_entity_get_participant, deleted_entities);
CU_TestDecl(ddsc_entity_get_participant, invalid_entities);
CU_TestDecl(ddsc_entity_get_parent, conditions);
CU_TestDecl(ddsc_entity_get_parent, pubsubtop);
CU_TestDecl(ddsc_entity_get_parent, deleted_entities);
CU_TestDecl(ddsc_entity_get_parent, invalid_entities);
CU_TestDecl(ddsc_entity_get_children, conditions);
CU_TestDecl(ddsc_entity_get_children, deleted_entities);
CU_TestDecl(ddsc_entity_get_children, invalid_entities);
CU_TestDecl(ddsc_entity_get_topic, data_entities);
CU_TestDecl(ddsc_entity_get_topic, deleted_entities);
CU_TestDecl(ddsc_entity_get_topic, invalid_entities);
CU_TestDecl(ddsc_entity_get_topic, non_data_entities);
CU_TestDecl(ddsc_entity_get_publisher, invalid_writers);
CU_TestDecl(ddsc_entity_get_publisher, non_writers);
CU_TestDecl(ddsc_entity_get_subscriber, readers);
CU_TestDecl(ddsc_entity_get_subscriber, deleted_readers);
CU_TestDecl(ddsc_entity_get_subscriber, invalid_readers);
CU_TestDecl(ddsc_entity_get_subscriber, non_readers);
CU_TestDecl(ddsc_entity_get_datareader, conditions);
CU_TestDecl(ddsc_entity_get_datareader, deleted_conds);
CU_TestDecl(ddsc_entity_get_datareader, invalid_conds);
CU_TestDecl(ddsc_entity_get_datareader, non_conds);
CU_TestDecl(ddsc_entity_status, publication_matched);
CU_TestDecl(ddsc_entity_status, subscription_matched);
CU_TestDecl(ddsc_entity, incompatible_qos);
CU_TestDecl(ddsc_entity, liveliness_changed);
CU_TestDecl(ddsc_entity, sample_rejected);
CU_TestDecl(ddsc_entity, sample_lost);
CU_TestDecl(ddsc_entity, data_available);
CU_TestDecl(ddsc_entity, all_data_available);
CU_TestDecl(ddsc_get_enabled_status, deleted_reader);
CU_TestDecl(ddsc_get_enabled_status, illegal);
CU_TestDecl(ddsc_set_enabled_status, deleted_reader);
CU_TestDecl(ddsc_set_enabled_status, illegal);
CU_TestDecl(ddsc_read_status, deleted_reader);
CU_TestDecl(ddsc_read_status, illegal);
CU_TestDecl(ddsc_read_status, invalid_status_on_reader);
CU_TestDecl(ddsc_read_status, invalid_status_on_writer);
CU_TestDecl(ddsc_take_status, deleted_reader);
CU_TestDecl(ddsc_take_status, illegal);
CU_TestDecl(ddsc_get_status_changes, deleted_reader);
CU_TestDecl(ddsc_get_status_changes, illegal);
CU_TestDecl(ddsc_triggered, deleted_reader);
CU_TestDecl(ddsc_get_inconsistent_topic_status, inconsistent_topic_status);
CU_TestDecl(ddsc_get_inconsistent_topic_status, null);
CU_TestDecl(ddsc_get_inconsistent_topic_status, deleted_topic);
CU_TestDecl(ddsc_get_publication_matched_status, null);
CU_TestDecl(ddsc_get_publication_matched_status, deleted_writer);
CU_TestDecl(ddsc_get_liveliness_lost_status, liveliness_lost_status);
CU_TestDecl(ddsc_get_liveliness_lost_status, null);
CU_TestDecl(ddsc_get_liveliness_lost_status, deleted_writer);
CU_TestDecl(ddsc_get_offered_deadline_missed_status, offered_deadline_missed_status);
CU_TestDecl(ddsc_get_offered_deadline_missed_status, null);
CU_TestDecl(ddsc_get_offered_deadline_missed_status, deleted_writer);
CU_TestDecl(ddsc_get_offered_incompatible_qos_status, null);
CU_TestDecl(ddsc_get_offered_incompatible_qos_status, deleted_writer);
CU_TestDecl(ddsc_get_subscription_matched_status, null);
CU_TestDecl(ddsc_get_subscription_matched_status, deleted_reader);
CU_TestDecl(ddsc_get_liveliness_changed_status, null);
CU_TestDecl(ddsc_get_liveliness_changed_status, deleted_reader);
CU_TestDecl(ddsc_get_sample_rejected_status, null);
CU_TestDecl(ddsc_get_sample_rejected_status, deleted_reader);
CU_TestDecl(ddsc_get_sample_lost_status, null);
CU_TestDecl(ddsc_get_sample_lost_status, deleted_reader);
CU_TestDecl(ddsc_get_requested_deadline_missed_status, requested_deadline_missed_status);
CU_TestDecl(ddsc_get_requested_deadline_missed_status, null);
CU_TestDecl(ddsc_get_requested_deadline_missed_status, deleted_reader);
CU_TestDecl(ddsc_get_requested_incompatible_qos_status, null);
CU_TestDecl(ddsc_get_requested_incompatible_qos_status, deleted_reader);
CU_TestDecl(ddsc_get_enabled_status, bad_param);
CU_TestDecl(ddsc_get_enabled_status, status_ok);
CU_TestDecl(ddsc_set_enabled_status, bad_param);
CU_TestDecl(ddsc_set_enabled_status, status_ok);
CU_TestDecl(ddsc_read_status, bad_param);
CU_TestDecl(ddsc_read_status, status_ok);
CU_TestDecl(ddsc_take_status, bad_param);
CU_TestDecl(ddsc_take_status, status_ok);
CU_TestDecl(ddsc_get_status_changes, bad_param);
CU_TestDecl(ddsc_get_status_changes, status_ok);
CU_TestDecl(ddsc_triggered, bad_param);
CU_TestDecl(ddsc_triggered, status_ok);
CU_TestDecl(ddsc_get_inconsistent_topic_status, bad_params);
CU_TestDecl(ddsc_get_inconsistent_topic_status, non_topics);
CU_TestDecl(ddsc_get_publication_matched_status, bad_params);
CU_TestDecl(ddsc_get_publication_matched_status, non_writers);
CU_TestDecl(ddsc_get_liveliness_lost_status, bad_params);
CU_TestDecl(ddsc_get_liveliness_lost_status, non_writers);
CU_TestDecl(ddsc_get_offered_deadline_missed_status, bad_params);
CU_TestDecl(ddsc_get_offered_deadline_missed_status, non_writers);
CU_TestDecl(ddsc_get_offered_incompatible_qos_status, bad_params);
CU_TestDecl(ddsc_get_offered_incompatible_qos_status, non_writers);
CU_TestDecl(ddsc_get_subscription_matched_status, bad_params);
CU_TestDecl(ddsc_get_subscription_matched_status, non_readers);
CU_TestDecl(ddsc_get_liveliness_changed_status, bad_params);
CU_TestDecl(ddsc_get_liveliness_changed_status, non_readers);
CU_TestDecl(ddsc_get_sample_rejected_status, bad_params);
CU_TestDecl(ddsc_get_sample_rejected_status, non_readers);
CU_TestDecl(ddsc_get_sample_lost_status, bad_params);
CU_TestDecl(ddsc_get_sample_lost_status, non_readers);
CU_TestDecl(ddsc_get_requested_deadline_missed_status, bad_params);
CU_TestDecl(ddsc_get_requested_deadline_missed_status, non_readers);
CU_TestDecl(ddsc_get_requested_incompatible_qos_status, bad_params);
CU_TestDecl(ddsc_get_requested_incompatible_qos_status, non_readers);
CU_TestDecl(ddsc_filter, basic);
CU_TestDecl(ddsc_filter, ownership);
CU_TestDecl(ddsc_filter, compat);
CU_TestDecl(ddsc_filter, get);
CU_TestDecl(ddsc_filter, getset_extended);
CU_TestDecl(ddsc_filter, sampleinfo);
CU_TestDecl(ddsc_instance_get_key, bad_entity);
CU_TestDecl(ddsc_instance_get_key, null_data);
CU_TestDecl(ddsc_instance_get_key, null_handle);
CU_TestDecl(ddsc_instance_get_key, registered_instance);
CU_TestDecl(ddsc_instance_get_key, readcondition);
CU_TestDecl(ddsc_instance_get_key, querycondition);
CU_TestDecl(ddsc_instance_handle, a);
CU_TestDecl(ddsc_instance_handle, md5);
CU_TestDecl(ddsc_listener, create_and_delete);
CU_TestDecl(ddsc_listener, reset);
CU_TestDecl(ddsc_listener, copy);
CU_TestDecl(ddsc_listener, merge);
CU_TestDecl(ddsc_listener, getters_setters);
CU_TestDecl(ddsc_listener, propagation);
CU_TestDecl(ddsc_listener, matched);
CU_TestDecl(ddsc_listener, publication_matched);
CU_TestDecl(ddsc_listener, subscription_matched);
CU_TestDecl(ddsc_listener, incompatible_qos);
CU_TestDecl(ddsc_listener, data_available);
CU_TestDecl(ddsc_listener, data_available_delete_writer);
CU_TestDecl(ddsc_listener, data_available_delete_writer_disposed);
CU_TestDecl(ddsc_listener, data_on_readers);
CU_TestDecl(ddsc_listener, sample_lost);
CU_TestDecl(ddsc_listener, sample_rejected);
CU_TestDecl(ddsc_listener, liveliness_changed);
CU_TestDecl(ddsc_liveliness, lease_duration);
CU_TestDecl(ddsc_liveliness, lease_duration_pwr);
CU_TestDecl(ddsc_liveliness, create_delete_writer_stress);
CU_TestDecl(ddsc_liveliness, status_counts);
CU_TestDecl(ddsc_liveliness, lease_duration_zero_or_one);
CU_TestDecl(ddsc_liveliness, listener_vs_getstatus);
CU_TestDecl(ddsc_liveliness, pmd_count);
CU_TestDecl(ddsc_liveliness, expire_liveliness_kinds);
CU_TestDecl(ddsc_liveliness, assert_liveliness);
CU_TestDecl(ddsc_loan, bad_params);
CU_TestDecl(ddsc_loan, success);
CU_TestDecl(ddsc_loan, take_cleanup);
CU_TestDecl(ddsc_loan, read_cleanup);
CU_TestDecl(ddsc_multi_sertype, local);
CU_TestDecl(ddsc_multi_sertype, remote);
CU_TestDecl(ddsc_multi_sertype, local_slowpath);
CU_TestDecl(ddsc_multi_sertype, remote_slowpath);
CU_TestDecl(ddsc_multi_sertype, transient_local);
CU_TestDecl(ddsc_participant, create_and_delete);
CU_TestDecl(ddsc_participant, create_with_no_conf_no_env);
CU_TestDecl(ddsc_participant, create_multiple_domains);
CU_TestDecl(ddsc_participant, create_with_conf_no_env);
CU_TestDecl(ddsc_participant_lookup, one);
CU_TestDecl(ddsc_participant_lookup, multiple);
CU_TestDecl(ddsc_participant_lookup, array_too_small);
CU_TestDecl(ddsc_participant_lookup, null_zero);
CU_TestDecl(ddsc_participant_lookup, null_nonzero);
CU_TestDecl(ddsc_participant_lookup, unknown_id);
CU_TestDecl(ddsc_participant_lookup, none);
CU_TestDecl(ddsc_participant_lookup, no_more);
CU_TestDecl(ddsc_participant_lookup, deleted);
CU_TestDecl(ddsc_publisher, create);
CU_TestDecl(ddsc_publisher, invalid_qos);
CU_TestDecl(ddsc_publisher, suspend_resume);
CU_TestDecl(ddsc_publisher, wait_for_acks);
CU_TestDecl(ddsc_publisher, coherency);
CU_TestDecl(ddsc_qos, copy_bad_source);
CU_TestDecl(ddsc_qos, copy_bad_destination);
CU_TestDecl(ddsc_qos, copy_with_partition);
CU_TestDecl(ddsc_qos, userdata);
CU_TestDecl(ddsc_qos, topicdata);
CU_TestDecl(ddsc_qos, groupdata);
CU_TestDecl(ddsc_qos, durability);
CU_TestDecl(ddsc_qos, history);
CU_TestDecl(ddsc_qos, resource_limits);
CU_TestDecl(ddsc_qos, presentation);
CU_TestDecl(ddsc_qos, lifespan);
CU_TestDecl(ddsc_qos, deadline);
CU_TestDecl(ddsc_qos, latency_budget);
CU_TestDecl(ddsc_qos, ownership);
CU_TestDecl(ddsc_qos, ownership_strength);
CU_TestDecl(ddsc_qos, liveliness);
CU_TestDecl(ddsc_qos, time_base_filter);
CU_TestDecl(ddsc_qos, partition);
CU_TestDecl(ddsc_qos, reliability);
CU_TestDecl(ddsc_qos, transport_priority);
CU_TestDecl(ddsc_qos, destination_order);
CU_TestDecl(ddsc_qos, writer_data_lifecycle);
CU_TestDecl(ddsc_qos, reader_data_lifecycle);
CU_TestDecl(ddsc_qos, durability_service);
CU_TestDecl(ddsc_qos, property);
CU_TestDecl(ddsc_qos, bproperty);
CU_TestDecl(ddsc_qos, property_mixed);
CU_TestDecl(ddsc_qos, type_consistency);
CU_TestDecl(ddsc_qosmatch, basic);
CU_TestDecl(ddsc_querycondition_create, second);
CU_TestDecl(ddsc_querycondition_create, deleted_reader);
CU_TestDecl(ddsc_querycondition_get_mask, deleted);
CU_TestDecl(ddsc_querycondition_get_mask, null);
CU_TestDecl(ddsc_querycondition_read, any);
CU_TestDecl(ddsc_querycondition_read, not_read_sample_state);
CU_TestDecl(ddsc_querycondition_read, read_sample_state);
CU_TestDecl(ddsc_querycondition_read, new_view_state);
CU_TestDecl(ddsc_querycondition_read, not_new_view_state);
CU_TestDecl(ddsc_querycondition_read, alive_instance_state);
CU_TestDecl(ddsc_querycondition_read, disposed_instance_state);
CU_TestDecl(ddsc_querycondition_read, no_writers_instance_state);
CU_TestDecl(ddsc_querycondition_read, combination_of_states);
CU_TestDecl(ddsc_querycondition_read, none);
CU_TestDecl(ddsc_querycondition_read, with_mask);
CU_TestDecl(ddsc_querycondition_read, already_deleted);
CU_TestDecl(ddsc_querycondition_take, any);
CU_TestDecl(ddsc_querycondition_take, not_read_sample_state);
CU_TestDecl(ddsc_querycondition_take, read_sample_state);
CU_TestDecl(ddsc_querycondition_take, new_view_state);
CU_TestDecl(ddsc_querycondition_take, not_new_view_state);
CU_TestDecl(ddsc_querycondition_take, alive_instance_state);
CU_TestDecl(ddsc_querycondition_take, disposed_instance_state);
CU_TestDecl(ddsc_querycondition_take, no_writers_instance_state);
CU_TestDecl(ddsc_querycondition_take, combination_of_states);
CU_TestDecl(ddsc_querycondition_take, none);
CU_TestDecl(ddsc_querycondition_take, with_mask);
CU_TestDecl(ddsc_querycondition_take, already_deleted);
CU_TestDecl(ddsc_querycondition_take, some_from_instance);
CU_TestDecl(ddsc_querycondition_create, invalid_readers);
CU_TestDecl(ddsc_querycondition_create, non_readers);
CU_TestDecl(ddsc_querycondition_get_mask, invalid_conditions);
CU_TestDecl(ddsc_querycondition_get_mask, non_conditions);
CU_TestDecl(ddsc_querycondition_get_mask, various_masks);
CU_TestDecl(ddsc_guardcond_create, cyclonedds);
CU_TestDecl(ddsc_guardcond_create, domain);
CU_TestDecl(ddsc_guardcond_create, participant);
CU_TestDecl(ddsc_guardcond, set_trigger);
CU_TestDecl(ddsc_guardcond, take_trigger);
CU_TestDecl(ddsc_guardcond, waitset);
CU_TestDecl(ddsc_guardcond, waitset_thread);
CU_TestDecl(ddsc_readcondition_create, second);
CU_TestDecl(ddsc_readcondition_create, deleted_reader);
CU_TestDecl(ddsc_readcondition_get_mask, deleted);
CU_TestDecl(ddsc_readcondition_get_mask, null);
CU_TestDecl(ddsc_readcondition_read, already_deleted);
CU_TestDecl(ddsc_readcondition_take, already_deleted);
CU_TestDecl(ddsc_readcondition, read);
CU_TestDecl(ddsc_readcondition, take);
CU_TestDecl(ddsc_readcondition, stress);
CU_TestDecl(ddsc_readcondition_create, invalid_readers);
CU_TestDecl(ddsc_readcondition_create, non_readers);
CU_TestDecl(ddsc_readcondition_get_mask, invalid_conditions);
CU_TestDecl(ddsc_readcondition_get_mask, non_conditions);
CU_TestDecl(ddsc_readcondition_get_mask, various_masks);
CU_TestDecl(ddsc_reader_create, invalid_qos_participant);
CU_TestDecl(ddsc_reader_create, invalid_qos_subscriber);
CU_TestDecl(ddsc_reader_create, wrong_participant);
CU_TestDecl(ddsc_reader_create, participant_mismatch);
CU_TestDecl(ddsc_read, already_deleted);
CU_TestDecl(ddsc_read, valid);
CU_TestDecl(ddsc_read_wl, already_deleted);
CU_TestDecl(ddsc_read_wl, valid);
CU_TestDecl(ddsc_read_mask, already_deleted);
CU_TestDecl(ddsc_read_mask, any);
CU_TestDecl(ddsc_read_mask, not_read_sample_state);
CU_TestDecl(ddsc_read_mask, read_sample_state);
CU_TestDecl(ddsc_read_mask, new_view_state);
CU_TestDecl(ddsc_read_mask, not_new_view_state);
CU_TestDecl(ddsc_read_mask, alive_instance_state);
CU_TestDecl(ddsc_read_mask, not_alive_instance_state);
CU_TestDecl(ddsc_read_mask, disposed_instance_state);
CU_TestDecl(ddsc_read_mask, no_writers_instance_state);
CU_TestDecl(ddsc_read_mask, combination_of_states);
CU_TestDecl(ddsc_read_mask_wl, already_deleted);
CU_TestDecl(ddsc_read_mask_wl, any);
CU_TestDecl(ddsc_read_mask_wl, not_read_sample_state);
CU_TestDecl(ddsc_read_mask_wl, read_sample_state);
CU_TestDecl(ddsc_read_mask_wl, new_view_state);
CU_TestDecl(ddsc_read_mask_wl, not_new_view_state);
CU_TestDecl(ddsc_read_mask_wl, alive_instance_state);
CU_TestDecl(ddsc_read_mask_wl, not_alive_instance_state);
CU_TestDecl(ddsc_read_mask_wl, disposed_instance_state);
CU_TestDecl(ddsc_read_mask_wl, no_writers_instance_state);
CU_TestDecl(ddsc_read_mask_wl, combination_of_states);
CU_TestDecl(ddsc_take, already_deleted);
CU_TestDecl(ddsc_take, valid);
CU_TestDecl(ddsc_take_wl, already_deleted);
CU_TestDecl(ddsc_take_wl, valid);
CU_TestDecl(ddsc_take_mask, already_deleted);
CU_TestDecl(ddsc_take_mask, any);
CU_TestDecl(ddsc_take_mask, not_read_sample_state);
CU_TestDecl(ddsc_take_mask, read_sample_state);
CU_TestDecl(ddsc_take_mask, new_view_state);
CU_TestDecl(ddsc_take_mask, not_new_view_state);
CU_TestDecl(ddsc_take_mask, alive_instance_state);
CU_TestDecl(ddsc_take_mask, not_alive_instance_state);
CU_TestDecl(ddsc_take_mask, disposed_instance_state);
CU_TestDecl(ddsc_take_mask, no_writers_instance_state);
CU_TestDecl(ddsc_take_mask, combination_of_states);
CU_TestDecl(ddsc_take_mask, take_instance_last_sample);
CU_TestDecl(ddsc_take_mask_wl, already_deleted);
CU_TestDecl(ddsc_take_mask_wl, any);
CU_TestDecl(ddsc_take_mask_wl, not_read_sample_state);
CU_TestDecl(ddsc_take_mask_wl, read_sample_state);
CU_TestDecl(ddsc_take_mask_wl, new_view_state);
CU_TestDecl(ddsc_take_mask_wl, not_new_view_state);
CU_TestDecl(ddsc_take_mask_wl, alive_instance_state);
CU_TestDecl(ddsc_take_mask_wl, not_alive_instance_state);
CU_TestDecl(ddsc_take_mask_wl, disposed_instance_state);
CU_TestDecl(ddsc_take_mask_wl, no_writers_instance_state);
CU_TestDecl(ddsc_take_mask_wl, combination_of_states);
CU_TestDecl(ddsc_reader_create, valid);
CU_TestDecl(ddsc_reader_create, non_participants_non_topics);
CU_TestDecl(ddsc_read, invalid_buffers);
CU_TestDecl(ddsc_read, invalid_readers);
CU_TestDecl(ddsc_read, non_readers);
CU_TestDecl(ddsc_read_wl, invalid_buffers);
CU_TestDecl(ddsc_read_wl, invalid_readers);
CU_TestDecl(ddsc_read_wl, non_readers);
CU_TestDecl(ddsc_read_mask, invalid_buffers);
CU_TestDecl(ddsc_read_mask, invalid_readers);
CU_TestDecl(ddsc_read_mask, non_readers);
CU_TestDecl(ddsc_read_mask_wl, invalid_buffers);
CU_TestDecl(ddsc_read_mask_wl, invalid_readers);
CU_TestDecl(ddsc_read_mask_wl, non_readers);
CU_TestDecl(ddsc_take, invalid_buffers);
CU_TestDecl(ddsc_take, invalid_readers);
CU_TestDecl(ddsc_take, non_readers);
CU_TestDecl(ddsc_take_wl, invalid_buffers);
CU_TestDecl(ddsc_take_wl, invalid_readers);
CU_TestDecl(ddsc_take_wl, non_readers);
CU_TestDecl(ddsc_take_mask, invalid_buffers);
CU_TestDecl(ddsc_take_mask, invalid_readers);
CU_TestDecl(ddsc_take_mask, non_readers);
CU_TestDecl(ddsc_take_mask_wl, invalid_buffers);
CU_TestDecl(ddsc_take_mask_wl, invalid_readers);
CU_TestDecl(ddsc_take_mask_wl, non_readers);
CU_TestDecl(ddsc_read_next, reader);
CU_TestDecl(ddsc_read_next_wl, reader);
CU_TestDecl(ddsc_take_next, reader);
CU_TestDecl(ddsc_take_next_wl, reader);
CU_TestDecl(ddsc_read_next, invalid_readers);
CU_TestDecl(ddsc_read_next, non_readers);
CU_TestDecl(ddsc_read_next, already_deleted);
CU_TestDecl(ddsc_read_next, invalid_buffers);
CU_TestDecl(ddsc_read_next_wl, invalid_readers);
CU_TestDecl(ddsc_read_next_wl, non_readers);
CU_TestDecl(ddsc_read_next_wl, already_deleted);
CU_TestDecl(ddsc_read_next_wl, invalid_buffers);
CU_TestDecl(ddsc_take_next, invalid_readers);
CU_TestDecl(ddsc_take_next, non_readers);
CU_TestDecl(ddsc_take_next, already_deleted);
CU_TestDecl(ddsc_take_next, invalid_buffers);
CU_TestDecl(ddsc_take_next_wl, invalid_readers);
CU_TestDecl(ddsc_take_next_wl, non_readers);
CU_TestDecl(ddsc_take_next_wl, already_deleted);
CU_TestDecl(ddsc_take_next_wl, invalid_buffers);
CU_TestDecl(ddsc_read_instance, reader);
CU_TestDecl(ddsc_read_instance_wl, reader);
CU_TestDecl(ddsc_read_instance_mask, reader);
CU_TestDecl(ddsc_read_instance_mask_wl, reader);
CU_TestDecl(ddsc_read_instance, readcondition);
CU_TestDecl(ddsc_read_instance_wl, readcondition);
CU_TestDecl(ddsc_read_instance_mask, readcondition);
CU_TestDecl(ddsc_read_instance_mask_wl, readcondition);
CU_TestDecl(ddsc_read_instance, querycondition);
CU_TestDecl(ddsc_read_instance_wl, querycondition);
CU_TestDecl(ddsc_read_instance_mask, querycondition);
CU_TestDecl(ddsc_read_instance_mask_wl, querycondition);
CU_TestDecl(ddsc_read_instance, invalid_params);
CU_TestDecl(ddsc_read_instance_wl, invalid_params);
CU_TestDecl(ddsc_read_instance_mask, invalid_params);
CU_TestDecl(ddsc_read_instance_mask_wl, invalid_params);
CU_TestDecl(ddsc_read_instance, invalid_handles);
CU_TestDecl(ddsc_read_instance_wl, invalid_handles);
CU_TestDecl(ddsc_read_instance_mask, invalid_handles);
CU_TestDecl(ddsc_read_instance_mask_wl, invalid_handles);
CU_TestDecl(ddsc_read_instance, invalid_readers);
CU_TestDecl(ddsc_read_instance_wl, invalid_readers);
CU_TestDecl(ddsc_read_instance_mask, invalid_readers);
CU_TestDecl(ddsc_read_instance_mask_wl, invalid_readers);
CU_TestDecl(ddsc_read_instance, non_readers);
CU_TestDecl(ddsc_read_instance_wl, non_readers);
CU_TestDecl(ddsc_read_instance_mask, non_readers);
CU_TestDecl(ddsc_read_instance_mask_wl, non_readers);
CU_TestDecl(ddsc_read_instance, already_deleted);
CU_TestDecl(ddsc_read_instance_wl, already_deleted);
CU_TestDecl(ddsc_read_instance_mask, already_deleted);
CU_TestDecl(ddsc_read_instance_mask_wl, already_deleted);
CU_TestDecl(ddsc_register_instance, deleted_entity);
CU_TestDecl(ddsc_register_instance, registering_new_instance);
CU_TestDecl(ddsc_register_instance, data_already_available);
CU_TestDecl(ddsc_register_instance, invalid_params);
CU_TestDecl(ddsc_register_instance, invalid_writers);
CU_TestDecl(ddsc_register_instance, non_writers);
CU_TestDecl(ddsc_subscriber, notify_readers);
CU_TestDecl(ddsc_subscriber, create);
CU_TestDecl(ddsc_subscriber, invalid_qos);
CU_TestDecl(ddsc_take_instance, reader);
CU_TestDecl(ddsc_take_instance_wl, reader);
CU_TestDecl(ddsc_take_instance_mask, reader);
CU_TestDecl(ddsc_take_instance_mask_wl, reader);
CU_TestDecl(ddsc_take_instance, readcondition);
CU_TestDecl(ddsc_take_instance_wl, readcondition);
CU_TestDecl(ddsc_take_instance_mask, readcondition);
CU_TestDecl(ddsc_take_instance_mask_wl, readcondition);
CU_TestDecl(ddsc_take_instance, querycondition);
CU_TestDecl(ddsc_take_instance_wl, querycondition);
CU_TestDecl(ddsc_take_instance_mask, querycondition);
CU_TestDecl(ddsc_take_instance_mask_wl, querycondition);
CU_TestDecl(ddsc_take_instance, invalid_params);
CU_TestDecl(ddsc_take_instance_wl, invalid_params);
CU_TestDecl(ddsc_take_instance_mask, invalid_params);
CU_TestDecl(ddsc_take_instance_mask_wl, invalid_params);
CU_TestDecl(ddsc_take_instance, invalid_handles);
CU_TestDecl(ddsc_take_instance_wl, invalid_handles);
CU_TestDecl(ddsc_take_instance_mask, invalid_handles);
CU_TestDecl(ddsc_take_instance_mask_wl, invalid_handles);
CU_TestDecl(ddsc_take_instance, invalid_readers);
CU_TestDecl(ddsc_take_instance_wl, invalid_readers);
CU_TestDecl(ddsc_take_instance_mask, invalid_readers);
CU_TestDecl(ddsc_take_instance_mask_wl, invalid_readers);
CU_TestDecl(ddsc_take_instance, non_readers);
CU_TestDecl(ddsc_take_instance_wl, non_readers);
CU_TestDecl(ddsc_take_instance_mask, non_readers);
CU_TestDecl(ddsc_take_instance_mask_wl, non_readers);
CU_TestDecl(ddsc_take_instance, already_deleted);
CU_TestDecl(ddsc_take_instance_wl, already_deleted);
CU_TestDecl(ddsc_take_instance_mask, already_deleted);
CU_TestDecl(ddsc_take_instance_mask_wl, already_deleted);
CU_TestDecl(ddsc_time, request_time);
CU_TestDecl(ddsc_topic_create, invalid_qos);
CU_TestDecl(ddsc_topic_create, non_participants);
CU_TestDecl(ddsc_topic_create, duplicate);
CU_TestDecl(ddsc_topic_create, same_name);
CU_TestDecl(ddsc_topic_create, recreate);
CU_TestDecl(ddsc_topic_create, desc_null);
CU_TestDecl(ddsc_topic_get_name, valid);
CU_TestDecl(ddsc_topic_get_name, too_small);
CU_TestDecl(ddsc_topic_get_name, non_topic);
CU_TestDecl(ddsc_topic_get_name, deleted);
CU_TestDecl(ddsc_topic_get_type_name, valid);
CU_TestDecl(ddsc_topic_get_type_name, too_small);
CU_TestDecl(ddsc_topic_get_type_name, non_topic);
CU_TestDecl(ddsc_topic_get_type_name, deleted);
CU_TestDecl(ddsc_topic_set_qos, valid);
CU_TestDecl(ddsc_topic_set_qos, inconsistent);
CU_TestDecl(ddsc_topic_set_qos, immutable);
CU_TestDecl(ddsc_topic_create, valid);
CU_TestDecl(ddsc_topic_create, invalid_names);
CU_TestDecl(ddsc_topic_get_name, invalid_params);
CU_TestDecl(ddsc_topic_get_type_name, invalid_params);
CU_TestDecl(ddsc_topic_find_local, domain);
CU_TestDecl(ddsc_topic_find_local, domain_delete_reversed);
CU_TestDecl(ddsc_topic_find_local, domain_delete_pp);
CU_TestDecl(ddsc_topic_find_local, domain_delete_pp_reversed);
CU_TestDecl(ddsc_topic_find_local, participant);
CU_TestDecl(ddsc_topic_find_local, non_participants);
CU_TestDecl(ddsc_topic_find_local, null);
CU_TestDecl(ddsc_topic_find_local, unknown);
CU_TestDecl(ddsc_topic_find_local, deleted);
CU_TestDecl(ddsc_transient_local, late_joiner);
CU_TestDecl(ddsc_types, long_arraytypekey);
CU_TestDecl(ddsc_types, longlong_arraytypekey);
CU_TestDecl(ddsc_types, unsignedshort_arraytypekey);
CU_TestDecl(ddsc_types, unsignedlong_arraytypekey);
CU_TestDecl(ddsc_types, unsignedlonglong_arraytypekey);
CU_TestDecl(ddsc_types, float_arraytypekey);
CU_TestDecl(ddsc_types, double_arraytypekey);
CU_TestDecl(ddsc_types, char_arraytypekey);
CU_TestDecl(ddsc_types, boolean_arraytypekey);
CU_TestDecl(ddsc_types, octet_arraytypekey);
CU_TestDecl(ddsc_types, alltypeskey);
CU_TestDecl(ddsc_unregister_instance, deleted);
CU_TestDecl(ddsc_unregister_instance, null);
CU_TestDecl(ddsc_unregister_instance, unregistering_old_instance);
CU_TestDecl(ddsc_unregister_instance_ts, deleted);
CU_TestDecl(ddsc_unregister_instance_ts, null);
CU_TestDecl(ddsc_unregister_instance_ts, unregistering_old_instance);
CU_TestDecl(ddsc_unregister_instance_ts, unregistering_past_sample);
CU_TestDecl(ddsc_unregister_instance_ih, deleted);
CU_TestDecl(ddsc_unregister_instance_ih, unregistering_old_instance);
CU_TestDecl(ddsc_unregister_instance_ih_ts, deleted);
CU_TestDecl(ddsc_unregister_instance_ih_ts, unregistering_old_instance);
CU_TestDecl(ddsc_unregister_instance_ih_ts, unregistering_past_sample);
CU_TestDecl(ddsc_unregister_instance_ih_ts, unregistering_instance);
CU_TestDecl(ddsc_unregister_instance, dispose_unregistered_sample);
CU_TestDecl(ddsc_unregister_instance_ts, dispose_unregistered_sample);
CU_TestDecl(ddsc_unregister_instance, invalid_writers);
CU_TestDecl(ddsc_unregister_instance, non_writers);
CU_TestDecl(ddsc_unregister_instance_ts, invalid_writers);
CU_TestDecl(ddsc_unregister_instance_ts, non_writers);
CU_TestDecl(ddsc_unregister_instance_ih, invalid_handles);
CU_TestDecl(ddsc_unregister_instance_ih, invalid_writers);
CU_TestDecl(ddsc_unregister_instance_ih, non_writers);
CU_TestDecl(ddsc_unregister_instance_ih_ts, invalid_handles);
CU_TestDecl(ddsc_unregister_instance_ih_ts, invalid_writers);
CU_TestDecl(ddsc_unregister_instance_ih_ts, non_writers);
CU_TestDecl(ddsc_unsupported, dds_begin_end_coherent);
CU_TestDecl(ddsc_unsupported, dds_suspend_resume);
CU_TestDecl(ddsc_unsupported, dds_get_instance_handle);
CU_TestDecl(ddsc_unsupported, dds_set_qos);
CU_TestDecl(ddsc_userdata, participant);
CU_TestDecl(ddsc_userdata, endpoint);
CU_TestDecl(ddsc_userdata, group);
CU_TestDecl(ddsc_userdata, topic);
CU_TestDecl(ddsc_waitset_create, second);
CU_TestDecl(ddsc_waitset_create, deleted_participant);
CU_TestDecl(ddsc_waitset_create, domain);
CU_TestDecl(ddsc_waitset_create, cyclonedds);
CU_TestDecl(ddsc_waitset_attach, deleted_waitset);
CU_TestDecl(ddsc_waitset_attach_detach, second);
CU_TestDecl(ddsc_waitset_attach_detach, various);
CU_TestDecl(ddsc_waitset_attach_detach, combinations);
CU_TestDecl(ddsc_waitset_delete_attached, self);
CU_TestDecl(ddsc_waitset_delete_attached, participant);
CU_TestDecl(ddsc_waitset_delete_attached, reader);
CU_TestDecl(ddsc_waitset_delete_attached, various);
CU_TestDecl(ddsc_waitset_set_trigger, deleted_waitset);
CU_TestDecl(ddsc_waitset_wait, deleted_waitset);
CU_TestDecl(ddsc_waitset_wait_until, deleted_waitset);
CU_TestDecl(ddsc_waitset_wait_until, past);
CU_TestDecl(ddsc_waitset_get_entities, no_array);
CU_TestDecl(ddsc_waitset_get_entities, deleted_waitset);
CU_TestDecl(ddsc_waitset_triggering, on_self);
CU_TestDecl(ddsc_waitset_triggering, on_reader);
CU_TestDecl(ddsc_waitset_triggering, on_readcondition);
CU_TestDecl(ddsc_waitset_create, invalid_params);
CU_TestDecl(ddsc_waitset_create, non_participants);
CU_TestDecl(ddsc_waitset_attach, invalid_params);
CU_TestDecl(ddsc_waitset_attach, invalid_waitsets);
CU_TestDecl(ddsc_waitset_attach, non_waitsets);
CU_TestDecl(ddsc_waitset_attach, scoping);
CU_TestDecl(ddsc_waitset_attach_detach, valid_entities);
CU_TestDecl(ddsc_waitset_detach, invalid_params);
CU_TestDecl(ddsc_waitset_detach, invalid_waitsets);
CU_TestDecl(ddsc_waitset_detach, valid_entities);
CU_TestDecl(ddsc_waitset_set_trigger, invalid_params);
CU_TestDecl(ddsc_waitset_set_trigger, non_waitsets);
CU_TestDecl(ddsc_waitset_wait, invalid_waitsets);
CU_TestDecl(ddsc_waitset_wait, non_waitsets);
CU_TestDecl(ddsc_waitset_wait, invalid_params);
CU_TestDecl(ddsc_waitset_wait_until, invalid_waitsets);
CU_TestDecl(ddsc_waitset_wait_until, non_waitsets);
CU_TestDecl(ddsc_waitset_wait_until, invalid_params);
CU_TestDecl(ddsc_waitset_get_entities, array_sizes);
CU_TestDecl(ddsc_waitset_get_entities, invalid_params);
CU_TestDecl(ddsc_waitset_get_entities, non_waitsets);
CU_TestDecl(ddsc_waitset_triggering, after_listener);
CU_TestDecl(ddsc_waitset, torture);
CU_TestDecl(ddsc_whc, check_end_state);
CU_TestDecl(ddsc_write, basic);
CU_TestDecl(ddsc_write, null_writer);
CU_TestDecl(ddsc_write, bad_writer);
CU_TestDecl(ddsc_write, closed_writer);
CU_TestDecl(ddsc_write, null_sample);
CU_TestDecl(ddsc_write_ts, basic);
CU_TestDecl(ddsc_write_ts, bad_timestamp);
CU_TestDecl(ddsc_write, simpletypes);
CU_TestDecl(ddsc_writetypes, various);
CU_TestDecl(ddsc_create_writer, basic);
CU_TestDecl(ddsc_create_writer, null_parent);
CU_TestDecl(ddsc_create_writer, bad_parent);
CU_TestDecl(ddsc_create_writer, participant);
CU_TestDecl(ddsc_create_writer, wrong_participant);
CU_TestDecl(ddsc_create_writer, publisher);
CU_TestDecl(ddsc_create_writer, deleted_publisher);
CU_TestDecl(ddsc_create_writer, null_topic);
CU_TestDecl(ddsc_create_writer, bad_topic);
CU_TestDecl(ddsc_create_writer, deleted_topic);
CU_TestDecl(ddsc_create_writer, participant_mismatch);
CU_TestDecl(ddsc_cdrstream, ser_des);
CU_TestDecl(ddsc_cdrstream, ser_des_multiple);
CU_TestDecl(ddsc_cdrstream, appendable_mutable);
CU_TestDecl(ddsc_cdrstream, min_xcdr_version);
CU_TestDecl(ddsc_cdrstream, check_optimize);
CU_TestDecl(ddsc_data_representation, xcdr1_xcdr2);
CU_TestDecl(ddsc_data_representation, matching);
CU_TestDecl(ddsc_data_representation, extensibility);
CU_TestDecl(ddsc_data_representation, update_qos);
CU_TestDecl(ddsc_lifespan, basic);
CU_TestDecl(ddsc_deadline, basic);
CU_TestDecl(ddsc_deadline, writer_types);
CU_TestDecl(ddsc_deadline, instances);

int main(int argc, char *argv[])
{
    int ret = EXIT_SUCCESS;

    if (parse_options(argc, argv) != 0) {
        usage(argv[0]);
        return EX_USAGE;
    } else if (opts.print_help) {
        help(argv[0]);
        return ret;
    } else if (CU_initialize_registry() != CUE_SUCCESS) {
        fprintf(stderr, "CU_initialize_registry: %s\n", CU_get_error_msg());
        return EX_SOFTWARE;
    }

/* CMake will expand the macro below to register all suites and tests. */

ADD_SUITE(ddsc_basic, NULL, NULL);
ADD_TEST(ddsc_basic, test, true);
ADD_SUITE(ddsc_builtin_topics, NULL, NULL);
ADD_TEST(ddsc_builtin_topics, availability_builtin_topics, true);
ADD_TEST(ddsc_builtin_topics, read_publication_data, true);
ADD_TEST(ddsc_builtin_topics, read_subscription_data, true);
ADD_TEST(ddsc_builtin_topics, read_participant_data, true);
ADD_TEST(ddsc_builtin_topics, read_topic_data, true);
ADD_TEST(ddsc_builtin_topics, same_subscriber, true);
ADD_TEST(ddsc_builtin_topics, builtin_qos, true);
ADD_TEST(ddsc_builtin_topics, read_nothing, true);
ADD_TEST(ddsc_builtin_topics, get_topic, true);
ADD_TEST(ddsc_builtin_topics, get_name, true);
ADD_TEST(ddsc_builtin_topics, get_type_name, true);
ADD_TEST(ddsc_builtin_topics, get_children, true);
ADD_TEST(ddsc_builtin_topics, cant_use_real_topic, true);
ADD_TEST(ddsc_builtin_topics, get_qos, true);
ADD_SUITE(ddsc_cdr, NULL, NULL);
ADD_SUITE(ddsc_cdr_sertopic, NULL, NULL);
ADD_TEST(ddsc_cdr, basic, true);
ADD_TEST(ddsc_cdr_sertopic, basic, true);
ADD_TEST(ddsc_cdr, forward, true);
ADD_TEST(ddsc_cdr_sertopic, forward, true);
ADD_TEST(ddsc_cdr, invalid_data, true);
ADD_TEST(ddsc_cdr_sertopic, invalid_data, true);
ADD_TEST(ddsc_cdr, timeout, true);
ADD_TEST(ddsc_cdr_sertopic, timeout, true);
ADD_SUITE(ddsc_config, NULL, NULL);
ADD_SUITE(ddsc_security_config, NULL, NULL);
ADD_SUITE(ddsc_security_qos, NULL, NULL);
ADD_TEST(ddsc_config, simple_udp, true);
ADD_TEST(ddsc_config, user_config, true);
ADD_TEST(ddsc_config, ignoredpartition, true);
ADD_TEST(ddsc_security_config, empty, true);
ADD_TEST(ddsc_security_qos, empty, true);
ADD_TEST(ddsc_config, invalid_envvar, true);
ADD_TEST(ddsc_config, too_deep_nesting, true);
ADD_TEST(ddsc_config, multiple_domains, true);
ADD_SUITE(ddsc_data_avail_stress, NULL, NULL);
ADD_TEST(ddsc_data_avail_stress, local, true);
ADD_TEST(ddsc_data_avail_stress, remote, true);
ADD_SUITE(ddsc_discstress, NULL, NULL);
ADD_TEST(ddsc_discstress, create_writer, true);
ADD_SUITE(ddsc_dispose, NULL, NULL);
ADD_SUITE(ddsc_dispose_ih, NULL, NULL);
ADD_SUITE(ddsc_dispose_ih_ts, NULL, NULL);
ADD_SUITE(ddsc_dispose_ts, NULL, NULL);
ADD_SUITE(ddsc_writedispose, NULL, NULL);
ADD_SUITE(ddsc_writedispose_ts, NULL, NULL);
ADD_TEST(ddsc_writedispose, deleted, true);
ADD_TEST(ddsc_writedispose, null, true);
ADD_TEST(ddsc_writedispose, disposing_old_instance, true);
ADD_TEST(ddsc_writedispose, disposing_new_instance, true);
ADD_TEST(ddsc_writedispose, timeout, true);
ADD_TEST(ddsc_writedispose_ts, deleted, true);
ADD_TEST(ddsc_writedispose_ts, null, true);
ADD_TEST(ddsc_writedispose_ts, timeout, true);
ADD_TEST(ddsc_writedispose_ts, disposing_old_instance, true);
ADD_TEST(ddsc_writedispose_ts, disposing_new_instance, true);
ADD_TEST(ddsc_writedispose_ts, disposing_past_sample, true);
ADD_TEST(ddsc_dispose, deleted, true);
ADD_TEST(ddsc_dispose, null, true);
ADD_TEST(ddsc_dispose, timeout, true);
ADD_TEST(ddsc_dispose, disposing_old_instance, true);
ADD_TEST(ddsc_dispose, disposing_new_instance, true);
ADD_TEST(ddsc_dispose_ts, deleted, true);
ADD_TEST(ddsc_dispose_ts, null, true);
ADD_TEST(ddsc_dispose_ts, timeout, true);
ADD_TEST(ddsc_dispose_ts, disposing_old_instance, true);
ADD_TEST(ddsc_dispose_ts, disposing_new_instance, true);
ADD_TEST(ddsc_dispose_ts, disposing_past_sample, true);
ADD_TEST(ddsc_dispose_ih, deleted, true);
ADD_TEST(ddsc_dispose_ih, disposing_old_instance, true);
ADD_TEST(ddsc_dispose_ih_ts, deleted, true);
ADD_TEST(ddsc_dispose_ih_ts, disposing_old_instance, true);
ADD_TEST(ddsc_dispose_ih_ts, disposing_past_sample, true);
ADD_TEST(ddsc_writedispose, invalid_writers, true);
ADD_TEST(ddsc_writedispose, non_writers, true);
ADD_TEST(ddsc_writedispose_ts, invalid_writers, true);
ADD_TEST(ddsc_writedispose_ts, non_writers, true);
ADD_TEST(ddsc_dispose, invalid_writers, true);
ADD_TEST(ddsc_dispose, non_writers, true);
ADD_TEST(ddsc_dispose_ts, invalid_writers, true);
ADD_TEST(ddsc_dispose_ts, non_writers, true);
ADD_TEST(ddsc_dispose_ih, invalid_handles, true);
ADD_TEST(ddsc_dispose_ih, invalid_writers, true);
ADD_TEST(ddsc_dispose_ih, non_writers, true);
ADD_TEST(ddsc_dispose_ih_ts, invalid_handles, true);
ADD_TEST(ddsc_dispose_ih_ts, invalid_writers, true);
ADD_TEST(ddsc_dispose_ih_ts, non_writers, true);
ADD_SUITE(ddsc_domain, NULL, NULL);
ADD_SUITE(ddsc_domain_create, NULL, NULL);
ADD_TEST(ddsc_domain, get_domainid, true);
ADD_TEST(ddsc_domain, delete_domain0, true);
ADD_TEST(ddsc_domain, delete_domainM, true);
ADD_TEST(ddsc_domain, delete_cyclonedds, true);
ADD_TEST(ddsc_domain_create, valid, true);
ADD_TEST(ddsc_domain_create, mismatch, true);
ADD_TEST(ddsc_domain_create, empty, true);
ADD_TEST(ddsc_domain_create, null, true);
ADD_TEST(ddsc_domain_create, after_domain, true);
ADD_TEST(ddsc_domain_create, after_participant, true);
ADD_TEST(ddsc_domain_create, diff, true);
ADD_TEST(ddsc_domain_create, domain_default, true);
ADD_TEST(ddsc_domain_create, invalid_xml, true);
ADD_TEST(ddsc_domain_create, raw_config, true);
ADD_SUITE(ddsc_domain, NULL, NULL);
ADD_TEST(ddsc_domain, torture_implicit, false);
ADD_TEST(ddsc_domain, torture_explicit, true);
ADD_SUITE(ddsc_entity, NULL, NULL);
ADD_TEST(ddsc_entity, create, true);
ADD_TEST(ddsc_entity, enable, true);
ADD_TEST(ddsc_entity, qos, true);
ADD_TEST(ddsc_entity, listener, true);
ADD_TEST(ddsc_entity, status, true);
ADD_TEST(ddsc_entity, guid, true);
ADD_TEST(ddsc_entity, instance_handle, true);
ADD_TEST(ddsc_entity, get_entities, true);
ADD_TEST(ddsc_entity, get_domainid, true);
ADD_TEST(ddsc_entity, delete, true);
ADD_SUITE(ddsc_entity_delete, NULL, NULL);
ADD_SUITE(ddsc_entity_explicit_subscriber, NULL, NULL);
ADD_SUITE(ddsc_entity_get_children, NULL, NULL);
ADD_SUITE(ddsc_entity_get_datareader, NULL, NULL);
ADD_SUITE(ddsc_entity_get_parent, NULL, NULL);
ADD_SUITE(ddsc_entity_get_participant, NULL, NULL);
ADD_SUITE(ddsc_entity_get_publisher, NULL, NULL);
ADD_SUITE(ddsc_entity_get_subscriber, NULL, NULL);
ADD_SUITE(ddsc_entity_get_topic, NULL, NULL);
ADD_SUITE(ddsc_entity_implicit, NULL, NULL);
ADD_SUITE(ddsc_entity_implicit_publisher, NULL, NULL);
ADD_SUITE(ddsc_entity_implicit_subscriber, NULL, NULL);
ADD_TEST(ddsc_entity_delete, recursive, true);
ADD_TEST(ddsc_entity_delete, recursive_with_deleted_topic, true);
ADD_TEST(ddsc_entity_get_parent, reader, true);
ADD_TEST(ddsc_entity_get_parent, writer, true);
ADD_TEST(ddsc_entity_get_parent, participant, true);
ADD_TEST(ddsc_entity_get_children, null, true);
ADD_TEST(ddsc_entity_get_children, invalid_size, true);
ADD_TEST(ddsc_entity_get_children, too_small, true);
ADD_TEST(ddsc_entity_get_children, participant, true);
ADD_TEST(ddsc_entity_get_children, topic, true);
ADD_TEST(ddsc_entity_get_children, publisher, true);
ADD_TEST(ddsc_entity_get_children, subscriber, true);
ADD_TEST(ddsc_entity_get_children, writer, true);
ADD_TEST(ddsc_entity_get_children, reader, true);
ADD_TEST(ddsc_entity_get_publisher, writer, true);
ADD_TEST(ddsc_entity_get_publisher, deleted_writer, true);
ADD_TEST(ddsc_entity_implicit_publisher, deleted, true);
ADD_TEST(ddsc_entity_implicit_publisher, invalid_topic, true);
ADD_TEST(ddsc_entity_implicit_subscriber, deleted, true);
ADD_TEST(ddsc_entity_explicit_subscriber, invalid_topic, true);
ADD_TEST(ddsc_entity_get_children, implicit_publisher, true);
ADD_TEST(ddsc_entity_get_children, implicit_subscriber, true);
ADD_TEST(ddsc_entity_get_parent, implicit_publisher, true);
ADD_TEST(ddsc_entity_get_parent, implicit_subscriber, true);
ADD_TEST(ddsc_entity_implicit, delete_publisher, true);
ADD_TEST(ddsc_entity_implicit, delete_subscriber, true);
ADD_TEST(ddsc_entity_get_participant, valid_entities, true);
ADD_TEST(ddsc_entity_get_participant, deleted_entities, true);
ADD_TEST(ddsc_entity_get_participant, invalid_entities, true);
ADD_TEST(ddsc_entity_get_parent, conditions, true);
ADD_TEST(ddsc_entity_get_parent, pubsubtop, true);
ADD_TEST(ddsc_entity_get_parent, deleted_entities, true);
ADD_TEST(ddsc_entity_get_parent, invalid_entities, true);
ADD_TEST(ddsc_entity_get_children, conditions, true);
ADD_TEST(ddsc_entity_get_children, deleted_entities, true);
ADD_TEST(ddsc_entity_get_children, invalid_entities, true);
ADD_TEST(ddsc_entity_get_topic, data_entities, true);
ADD_TEST(ddsc_entity_get_topic, deleted_entities, true);
ADD_TEST(ddsc_entity_get_topic, invalid_entities, true);
ADD_TEST(ddsc_entity_get_topic, non_data_entities, true);
ADD_TEST(ddsc_entity_get_publisher, invalid_writers, true);
ADD_TEST(ddsc_entity_get_publisher, non_writers, true);
ADD_TEST(ddsc_entity_get_subscriber, readers, true);
ADD_TEST(ddsc_entity_get_subscriber, deleted_readers, true);
ADD_TEST(ddsc_entity_get_subscriber, invalid_readers, true);
ADD_TEST(ddsc_entity_get_subscriber, non_readers, true);
ADD_TEST(ddsc_entity_get_datareader, conditions, true);
ADD_TEST(ddsc_entity_get_datareader, deleted_conds, true);
ADD_TEST(ddsc_entity_get_datareader, invalid_conds, true);
ADD_TEST(ddsc_entity_get_datareader, non_conds, true);
ADD_SUITE(ddsc_entity, NULL, NULL);
ADD_SUITE(ddsc_entity_status, NULL, NULL);
ADD_SUITE(ddsc_get_enabled_status, NULL, NULL);
ADD_SUITE(ddsc_get_inconsistent_topic_status, NULL, NULL);
ADD_SUITE(ddsc_get_liveliness_changed_status, NULL, NULL);
ADD_SUITE(ddsc_get_liveliness_lost_status, NULL, NULL);
ADD_SUITE(ddsc_get_offered_deadline_missed_status, NULL, NULL);
ADD_SUITE(ddsc_get_offered_incompatible_qos_status, NULL, NULL);
ADD_SUITE(ddsc_get_publication_matched_status, NULL, NULL);
ADD_SUITE(ddsc_get_requested_deadline_missed_status, NULL, NULL);
ADD_SUITE(ddsc_get_requested_incompatible_qos_status, NULL, NULL);
ADD_SUITE(ddsc_get_sample_lost_status, NULL, NULL);
ADD_SUITE(ddsc_get_sample_rejected_status, NULL, NULL);
ADD_SUITE(ddsc_get_status_changes, NULL, NULL);
ADD_SUITE(ddsc_get_subscription_matched_status, NULL, NULL);
ADD_SUITE(ddsc_read_status, NULL, NULL);
ADD_SUITE(ddsc_set_enabled_status, NULL, NULL);
ADD_SUITE(ddsc_take_status, NULL, NULL);
ADD_SUITE(ddsc_triggered, NULL, NULL);
ADD_TEST(ddsc_entity_status, publication_matched, true);
ADD_TEST(ddsc_entity_status, subscription_matched, true);
ADD_TEST(ddsc_entity, incompatible_qos, true);
ADD_TEST(ddsc_entity, liveliness_changed, true);
ADD_TEST(ddsc_entity, sample_rejected, true);
ADD_TEST(ddsc_entity, sample_lost, true);
ADD_TEST(ddsc_entity, data_available, true);
ADD_TEST(ddsc_entity, all_data_available, true);
ADD_TEST(ddsc_get_enabled_status, deleted_reader, true);
ADD_TEST(ddsc_get_enabled_status, illegal, true);
ADD_TEST(ddsc_set_enabled_status, deleted_reader, true);
ADD_TEST(ddsc_set_enabled_status, illegal, true);
ADD_TEST(ddsc_read_status, deleted_reader, true);
ADD_TEST(ddsc_read_status, illegal, true);
ADD_TEST(ddsc_read_status, invalid_status_on_reader, true);
ADD_TEST(ddsc_read_status, invalid_status_on_writer, true);
ADD_TEST(ddsc_take_status, deleted_reader, true);
ADD_TEST(ddsc_take_status, illegal, true);
ADD_TEST(ddsc_get_status_changes, deleted_reader, true);
ADD_TEST(ddsc_get_status_changes, illegal, true);
ADD_TEST(ddsc_triggered, deleted_reader, true);
ADD_TEST(ddsc_get_inconsistent_topic_status, inconsistent_topic_status, true);
ADD_TEST(ddsc_get_inconsistent_topic_status, null, true);
ADD_TEST(ddsc_get_inconsistent_topic_status, deleted_topic, true);
ADD_TEST(ddsc_get_publication_matched_status, null, true);
ADD_TEST(ddsc_get_publication_matched_status, deleted_writer, true);
ADD_TEST(ddsc_get_liveliness_lost_status, liveliness_lost_status, true);
ADD_TEST(ddsc_get_liveliness_lost_status, null, true);
ADD_TEST(ddsc_get_liveliness_lost_status, deleted_writer, true);
ADD_TEST(ddsc_get_offered_deadline_missed_status, offered_deadline_missed_status, true);
ADD_TEST(ddsc_get_offered_deadline_missed_status, null, true);
ADD_TEST(ddsc_get_offered_deadline_missed_status, deleted_writer, true);
ADD_TEST(ddsc_get_offered_incompatible_qos_status, null, true);
ADD_TEST(ddsc_get_offered_incompatible_qos_status, deleted_writer, true);
ADD_TEST(ddsc_get_subscription_matched_status, null, true);
ADD_TEST(ddsc_get_subscription_matched_status, deleted_reader, true);
ADD_TEST(ddsc_get_liveliness_changed_status, null, true);
ADD_TEST(ddsc_get_liveliness_changed_status, deleted_reader, true);
ADD_TEST(ddsc_get_sample_rejected_status, null, true);
ADD_TEST(ddsc_get_sample_rejected_status, deleted_reader, true);
ADD_TEST(ddsc_get_sample_lost_status, null, true);
ADD_TEST(ddsc_get_sample_lost_status, deleted_reader, true);
ADD_TEST(ddsc_get_requested_deadline_missed_status, requested_deadline_missed_status, true);
ADD_TEST(ddsc_get_requested_deadline_missed_status, null, true);
ADD_TEST(ddsc_get_requested_deadline_missed_status, deleted_reader, true);
ADD_TEST(ddsc_get_requested_incompatible_qos_status, null, true);
ADD_TEST(ddsc_get_requested_incompatible_qos_status, deleted_reader, true);
ADD_TEST(ddsc_get_enabled_status, bad_param, true);
ADD_TEST(ddsc_get_enabled_status, status_ok, true);
ADD_TEST(ddsc_set_enabled_status, bad_param, true);
ADD_TEST(ddsc_set_enabled_status, status_ok, true);
ADD_TEST(ddsc_read_status, bad_param, true);
ADD_TEST(ddsc_read_status, status_ok, true);
ADD_TEST(ddsc_take_status, bad_param, true);
ADD_TEST(ddsc_take_status, status_ok, true);
ADD_TEST(ddsc_get_status_changes, bad_param, true);
ADD_TEST(ddsc_get_status_changes, status_ok, true);
ADD_TEST(ddsc_triggered, bad_param, true);
ADD_TEST(ddsc_triggered, status_ok, true);
ADD_TEST(ddsc_get_inconsistent_topic_status, bad_params, true);
ADD_TEST(ddsc_get_inconsistent_topic_status, non_topics, true);
ADD_TEST(ddsc_get_publication_matched_status, bad_params, true);
ADD_TEST(ddsc_get_publication_matched_status, non_writers, true);
ADD_TEST(ddsc_get_liveliness_lost_status, bad_params, true);
ADD_TEST(ddsc_get_liveliness_lost_status, non_writers, true);
ADD_TEST(ddsc_get_offered_deadline_missed_status, bad_params, true);
ADD_TEST(ddsc_get_offered_deadline_missed_status, non_writers, true);
ADD_TEST(ddsc_get_offered_incompatible_qos_status, bad_params, true);
ADD_TEST(ddsc_get_offered_incompatible_qos_status, non_writers, true);
ADD_TEST(ddsc_get_subscription_matched_status, bad_params, true);
ADD_TEST(ddsc_get_subscription_matched_status, non_readers, true);
ADD_TEST(ddsc_get_liveliness_changed_status, bad_params, true);
ADD_TEST(ddsc_get_liveliness_changed_status, non_readers, true);
ADD_TEST(ddsc_get_sample_rejected_status, bad_params, true);
ADD_TEST(ddsc_get_sample_rejected_status, non_readers, true);
ADD_TEST(ddsc_get_sample_lost_status, bad_params, true);
ADD_TEST(ddsc_get_sample_lost_status, non_readers, true);
ADD_TEST(ddsc_get_requested_deadline_missed_status, bad_params, true);
ADD_TEST(ddsc_get_requested_deadline_missed_status, non_readers, true);
ADD_TEST(ddsc_get_requested_incompatible_qos_status, bad_params, true);
ADD_TEST(ddsc_get_requested_incompatible_qos_status, non_readers, true);
ADD_SUITE(ddsc_filter, NULL, NULL);
ADD_TEST(ddsc_filter, basic, true);
ADD_TEST(ddsc_filter, ownership, true);
ADD_TEST(ddsc_filter, compat, true);
ADD_TEST(ddsc_filter, get, true);
ADD_TEST(ddsc_filter, getset_extended, true);
ADD_TEST(ddsc_filter, sampleinfo, true);
ADD_SUITE(ddsc_instance_get_key, NULL, NULL);
ADD_TEST(ddsc_instance_get_key, bad_entity, true);
ADD_TEST(ddsc_instance_get_key, null_data, true);
ADD_TEST(ddsc_instance_get_key, null_handle, true);
ADD_TEST(ddsc_instance_get_key, registered_instance, true);
ADD_TEST(ddsc_instance_get_key, readcondition, true);
ADD_TEST(ddsc_instance_get_key, querycondition, true);
ADD_SUITE(ddsc_instance_handle, NULL, NULL);
ADD_TEST(ddsc_instance_handle, a, true);
ADD_TEST(ddsc_instance_handle, md5, true);
ADD_SUITE(ddsc_listener, NULL, NULL);
ADD_TEST(ddsc_listener, create_and_delete, true);
ADD_TEST(ddsc_listener, reset, true);
ADD_TEST(ddsc_listener, copy, true);
ADD_TEST(ddsc_listener, merge, true);
ADD_TEST(ddsc_listener, getters_setters, true);
ADD_TEST(ddsc_listener, propagation, true);
ADD_TEST(ddsc_listener, matched, true);
ADD_TEST(ddsc_listener, publication_matched, true);
ADD_TEST(ddsc_listener, subscription_matched, true);
ADD_TEST(ddsc_listener, incompatible_qos, true);
ADD_TEST(ddsc_listener, data_available, true);
ADD_TEST(ddsc_listener, data_available_delete_writer, true);
ADD_TEST(ddsc_listener, data_available_delete_writer_disposed, true);
ADD_TEST(ddsc_listener, data_on_readers, true);
ADD_TEST(ddsc_listener, sample_lost, true);
ADD_TEST(ddsc_listener, sample_rejected, true);
ADD_TEST(ddsc_listener, liveliness_changed, true);
ADD_SUITE(ddsc_liveliness, NULL, NULL);
ADD_TEST(ddsc_liveliness, lease_duration, true);
ADD_TEST(ddsc_liveliness, lease_duration_pwr, true);
ADD_TEST(ddsc_liveliness, create_delete_writer_stress, true);
ADD_TEST(ddsc_liveliness, status_counts, true);
ADD_TEST(ddsc_liveliness, lease_duration_zero_or_one, true);
ADD_TEST(ddsc_liveliness, listener_vs_getstatus, true);
ADD_TEST(ddsc_liveliness, pmd_count, true);
ADD_TEST(ddsc_liveliness, expire_liveliness_kinds, true);
ADD_TEST(ddsc_liveliness, assert_liveliness, true);
ADD_SUITE(ddsc_loan, NULL, NULL);
ADD_TEST(ddsc_loan, bad_params, true);
ADD_TEST(ddsc_loan, success, true);
ADD_TEST(ddsc_loan, take_cleanup, true);
ADD_TEST(ddsc_loan, read_cleanup, true);
ADD_SUITE(ddsc_multi_sertype, NULL, NULL);
ADD_TEST(ddsc_multi_sertype, local, true);
ADD_TEST(ddsc_multi_sertype, remote, true);
ADD_TEST(ddsc_multi_sertype, local_slowpath, true);
ADD_TEST(ddsc_multi_sertype, remote_slowpath, true);
ADD_TEST(ddsc_multi_sertype, transient_local, true);
ADD_SUITE(ddsc_participant, NULL, NULL);
ADD_SUITE(ddsc_participant_lookup, NULL, NULL);
ADD_TEST(ddsc_participant, create_and_delete, true);
ADD_TEST(ddsc_participant, create_with_no_conf_no_env, true);
ADD_TEST(ddsc_participant, create_multiple_domains, true);
ADD_TEST(ddsc_participant, create_with_conf_no_env, true);
ADD_TEST(ddsc_participant_lookup, one, true);
ADD_TEST(ddsc_participant_lookup, multiple, true);
ADD_TEST(ddsc_participant_lookup, array_too_small, true);
ADD_TEST(ddsc_participant_lookup, null_zero, true);
ADD_TEST(ddsc_participant_lookup, null_nonzero, true);
ADD_TEST(ddsc_participant_lookup, unknown_id, true);
ADD_TEST(ddsc_participant_lookup, none, true);
ADD_TEST(ddsc_participant_lookup, no_more, true);
ADD_TEST(ddsc_participant_lookup, deleted, true);
ADD_SUITE(ddsc_publisher, NULL, NULL);
ADD_TEST(ddsc_publisher, create, true);
ADD_TEST(ddsc_publisher, invalid_qos, true);
ADD_TEST(ddsc_publisher, suspend_resume, true);
ADD_TEST(ddsc_publisher, wait_for_acks, true);
ADD_TEST(ddsc_publisher, coherency, true);
ADD_SUITE(ddsc_qos, NULL, NULL);
ADD_TEST(ddsc_qos, copy_bad_source, true);
ADD_TEST(ddsc_qos, copy_bad_destination, true);
ADD_TEST(ddsc_qos, copy_with_partition, true);
ADD_TEST(ddsc_qos, userdata, true);
ADD_TEST(ddsc_qos, topicdata, true);
ADD_TEST(ddsc_qos, groupdata, true);
ADD_TEST(ddsc_qos, durability, true);
ADD_TEST(ddsc_qos, history, true);
ADD_TEST(ddsc_qos, resource_limits, true);
ADD_TEST(ddsc_qos, presentation, true);
ADD_TEST(ddsc_qos, lifespan, true);
ADD_TEST(ddsc_qos, deadline, true);
ADD_TEST(ddsc_qos, latency_budget, true);
ADD_TEST(ddsc_qos, ownership, true);
ADD_TEST(ddsc_qos, ownership_strength, true);
ADD_TEST(ddsc_qos, liveliness, true);
ADD_TEST(ddsc_qos, time_base_filter, true);
ADD_TEST(ddsc_qos, partition, true);
ADD_TEST(ddsc_qos, reliability, true);
ADD_TEST(ddsc_qos, transport_priority, true);
ADD_TEST(ddsc_qos, destination_order, true);
ADD_TEST(ddsc_qos, writer_data_lifecycle, true);
ADD_TEST(ddsc_qos, reader_data_lifecycle, true);
ADD_TEST(ddsc_qos, durability_service, true);
ADD_TEST(ddsc_qos, property, true);
ADD_TEST(ddsc_qos, bproperty, true);
ADD_TEST(ddsc_qos, property_mixed, true);
ADD_TEST(ddsc_qos, type_consistency, true);
ADD_SUITE(ddsc_qosmatch, NULL, NULL);
ADD_TEST(ddsc_qosmatch, basic, true);
ADD_SUITE(ddsc_querycondition_create, NULL, NULL);
ADD_SUITE(ddsc_querycondition_get_mask, NULL, NULL);
ADD_SUITE(ddsc_querycondition_read, NULL, NULL);
ADD_SUITE(ddsc_querycondition_take, NULL, NULL);
ADD_TEST(ddsc_querycondition_create, second, true);
ADD_TEST(ddsc_querycondition_create, deleted_reader, true);
ADD_TEST(ddsc_querycondition_get_mask, deleted, true);
ADD_TEST(ddsc_querycondition_get_mask, null, true);
ADD_TEST(ddsc_querycondition_read, any, true);
ADD_TEST(ddsc_querycondition_read, not_read_sample_state, true);
ADD_TEST(ddsc_querycondition_read, read_sample_state, true);
ADD_TEST(ddsc_querycondition_read, new_view_state, true);
ADD_TEST(ddsc_querycondition_read, not_new_view_state, true);
ADD_TEST(ddsc_querycondition_read, alive_instance_state, true);
ADD_TEST(ddsc_querycondition_read, disposed_instance_state, true);
ADD_TEST(ddsc_querycondition_read, no_writers_instance_state, true);
ADD_TEST(ddsc_querycondition_read, combination_of_states, true);
ADD_TEST(ddsc_querycondition_read, none, true);
ADD_TEST(ddsc_querycondition_read, with_mask, true);
ADD_TEST(ddsc_querycondition_read, already_deleted, true);
ADD_TEST(ddsc_querycondition_take, any, true);
ADD_TEST(ddsc_querycondition_take, not_read_sample_state, true);
ADD_TEST(ddsc_querycondition_take, read_sample_state, true);
ADD_TEST(ddsc_querycondition_take, new_view_state, true);
ADD_TEST(ddsc_querycondition_take, not_new_view_state, true);
ADD_TEST(ddsc_querycondition_take, alive_instance_state, true);
ADD_TEST(ddsc_querycondition_take, disposed_instance_state, true);
ADD_TEST(ddsc_querycondition_take, no_writers_instance_state, true);
ADD_TEST(ddsc_querycondition_take, combination_of_states, true);
ADD_TEST(ddsc_querycondition_take, none, true);
ADD_TEST(ddsc_querycondition_take, with_mask, true);
ADD_TEST(ddsc_querycondition_take, already_deleted, true);
ADD_TEST(ddsc_querycondition_take, some_from_instance, true);
ADD_TEST(ddsc_querycondition_create, invalid_readers, true);
ADD_TEST(ddsc_querycondition_create, non_readers, true);
ADD_TEST(ddsc_querycondition_get_mask, invalid_conditions, true);
ADD_TEST(ddsc_querycondition_get_mask, non_conditions, true);
ADD_TEST(ddsc_querycondition_get_mask, various_masks, true);
ADD_SUITE(ddsc_guardcond, NULL, NULL);
ADD_SUITE(ddsc_guardcond_create, NULL, NULL);
ADD_TEST(ddsc_guardcond_create, cyclonedds, true);
ADD_TEST(ddsc_guardcond_create, domain, true);
ADD_TEST(ddsc_guardcond_create, participant, true);
ADD_TEST(ddsc_guardcond, set_trigger, true);
ADD_TEST(ddsc_guardcond, take_trigger, true);
ADD_TEST(ddsc_guardcond, waitset, true);
ADD_TEST(ddsc_guardcond, waitset_thread, true);
ADD_SUITE(ddsc_readcondition, NULL, NULL);
ADD_SUITE(ddsc_readcondition_create, NULL, NULL);
ADD_SUITE(ddsc_readcondition_get_mask, NULL, NULL);
ADD_SUITE(ddsc_readcondition_read, NULL, NULL);
ADD_SUITE(ddsc_readcondition_take, NULL, NULL);
ADD_TEST(ddsc_readcondition_create, second, true);
ADD_TEST(ddsc_readcondition_create, deleted_reader, true);
ADD_TEST(ddsc_readcondition_get_mask, deleted, true);
ADD_TEST(ddsc_readcondition_get_mask, null, true);
ADD_TEST(ddsc_readcondition_read, already_deleted, true);
ADD_TEST(ddsc_readcondition_take, already_deleted, true);
ADD_TEST(ddsc_readcondition, read, true);
ADD_TEST(ddsc_readcondition, take, true);
ADD_TEST(ddsc_readcondition, stress, true);
ADD_TEST(ddsc_readcondition_create, invalid_readers, true);
ADD_TEST(ddsc_readcondition_create, non_readers, true);
ADD_TEST(ddsc_readcondition_get_mask, invalid_conditions, true);
ADD_TEST(ddsc_readcondition_get_mask, non_conditions, true);
ADD_TEST(ddsc_readcondition_get_mask, various_masks, true);
ADD_SUITE(ddsc_read, NULL, NULL);
ADD_SUITE(ddsc_read_mask, NULL, NULL);
ADD_SUITE(ddsc_read_mask_wl, NULL, NULL);
ADD_SUITE(ddsc_read_wl, NULL, NULL);
ADD_SUITE(ddsc_reader_create, NULL, NULL);
ADD_SUITE(ddsc_take, NULL, NULL);
ADD_SUITE(ddsc_take_mask, NULL, NULL);
ADD_SUITE(ddsc_take_mask_wl, NULL, NULL);
ADD_SUITE(ddsc_take_wl, NULL, NULL);
ADD_TEST(ddsc_reader_create, invalid_qos_participant, true);
ADD_TEST(ddsc_reader_create, invalid_qos_subscriber, true);
ADD_TEST(ddsc_reader_create, wrong_participant, true);
ADD_TEST(ddsc_reader_create, participant_mismatch, true);
ADD_TEST(ddsc_read, already_deleted, true);
ADD_TEST(ddsc_read, valid, true);
ADD_TEST(ddsc_read_wl, already_deleted, true);
ADD_TEST(ddsc_read_wl, valid, true);
ADD_TEST(ddsc_read_mask, already_deleted, true);
ADD_TEST(ddsc_read_mask, any, true);
ADD_TEST(ddsc_read_mask, not_read_sample_state, true);
ADD_TEST(ddsc_read_mask, read_sample_state, true);
ADD_TEST(ddsc_read_mask, new_view_state, true);
ADD_TEST(ddsc_read_mask, not_new_view_state, true);
ADD_TEST(ddsc_read_mask, alive_instance_state, true);
ADD_TEST(ddsc_read_mask, not_alive_instance_state, true);
ADD_TEST(ddsc_read_mask, disposed_instance_state, true);
ADD_TEST(ddsc_read_mask, no_writers_instance_state, true);
ADD_TEST(ddsc_read_mask, combination_of_states, true);
ADD_TEST(ddsc_read_mask_wl, already_deleted, true);
ADD_TEST(ddsc_read_mask_wl, any, true);
ADD_TEST(ddsc_read_mask_wl, not_read_sample_state, true);
ADD_TEST(ddsc_read_mask_wl, read_sample_state, true);
ADD_TEST(ddsc_read_mask_wl, new_view_state, true);
ADD_TEST(ddsc_read_mask_wl, not_new_view_state, true);
ADD_TEST(ddsc_read_mask_wl, alive_instance_state, true);
ADD_TEST(ddsc_read_mask_wl, not_alive_instance_state, true);
ADD_TEST(ddsc_read_mask_wl, disposed_instance_state, true);
ADD_TEST(ddsc_read_mask_wl, no_writers_instance_state, true);
ADD_TEST(ddsc_read_mask_wl, combination_of_states, true);
ADD_TEST(ddsc_take, already_deleted, true);
ADD_TEST(ddsc_take, valid, true);
ADD_TEST(ddsc_take_wl, already_deleted, true);
ADD_TEST(ddsc_take_wl, valid, true);
ADD_TEST(ddsc_take_mask, already_deleted, true);
ADD_TEST(ddsc_take_mask, any, true);
ADD_TEST(ddsc_take_mask, not_read_sample_state, true);
ADD_TEST(ddsc_take_mask, read_sample_state, true);
ADD_TEST(ddsc_take_mask, new_view_state, true);
ADD_TEST(ddsc_take_mask, not_new_view_state, true);
ADD_TEST(ddsc_take_mask, alive_instance_state, true);
ADD_TEST(ddsc_take_mask, not_alive_instance_state, true);
ADD_TEST(ddsc_take_mask, disposed_instance_state, true);
ADD_TEST(ddsc_take_mask, no_writers_instance_state, true);
ADD_TEST(ddsc_take_mask, combination_of_states, true);
ADD_TEST(ddsc_take_mask, take_instance_last_sample, true);
ADD_TEST(ddsc_take_mask_wl, already_deleted, true);
ADD_TEST(ddsc_take_mask_wl, any, true);
ADD_TEST(ddsc_take_mask_wl, not_read_sample_state, true);
ADD_TEST(ddsc_take_mask_wl, read_sample_state, true);
ADD_TEST(ddsc_take_mask_wl, new_view_state, true);
ADD_TEST(ddsc_take_mask_wl, not_new_view_state, true);
ADD_TEST(ddsc_take_mask_wl, alive_instance_state, true);
ADD_TEST(ddsc_take_mask_wl, not_alive_instance_state, true);
ADD_TEST(ddsc_take_mask_wl, disposed_instance_state, true);
ADD_TEST(ddsc_take_mask_wl, no_writers_instance_state, true);
ADD_TEST(ddsc_take_mask_wl, combination_of_states, true);
ADD_TEST(ddsc_reader_create, valid, true);
ADD_TEST(ddsc_reader_create, non_participants_non_topics, true);
ADD_TEST(ddsc_read, invalid_buffers, true);
ADD_TEST(ddsc_read, invalid_readers, true);
ADD_TEST(ddsc_read, non_readers, true);
ADD_TEST(ddsc_read_wl, invalid_buffers, true);
ADD_TEST(ddsc_read_wl, invalid_readers, true);
ADD_TEST(ddsc_read_wl, non_readers, true);
ADD_TEST(ddsc_read_mask, invalid_buffers, true);
ADD_TEST(ddsc_read_mask, invalid_readers, true);
ADD_TEST(ddsc_read_mask, non_readers, true);
ADD_TEST(ddsc_read_mask_wl, invalid_buffers, true);
ADD_TEST(ddsc_read_mask_wl, invalid_readers, true);
ADD_TEST(ddsc_read_mask_wl, non_readers, true);
ADD_TEST(ddsc_take, invalid_buffers, true);
ADD_TEST(ddsc_take, invalid_readers, true);
ADD_TEST(ddsc_take, non_readers, true);
ADD_TEST(ddsc_take_wl, invalid_buffers, true);
ADD_TEST(ddsc_take_wl, invalid_readers, true);
ADD_TEST(ddsc_take_wl, non_readers, true);
ADD_TEST(ddsc_take_mask, invalid_buffers, true);
ADD_TEST(ddsc_take_mask, invalid_readers, true);
ADD_TEST(ddsc_take_mask, non_readers, true);
ADD_TEST(ddsc_take_mask_wl, invalid_buffers, true);
ADD_TEST(ddsc_take_mask_wl, invalid_readers, true);
ADD_TEST(ddsc_take_mask_wl, non_readers, true);
ADD_SUITE(ddsc_read_next, NULL, NULL);
ADD_SUITE(ddsc_read_next_wl, NULL, NULL);
ADD_SUITE(ddsc_take_next, NULL, NULL);
ADD_SUITE(ddsc_take_next_wl, NULL, NULL);
ADD_TEST(ddsc_read_next, reader, true);
ADD_TEST(ddsc_read_next_wl, reader, true);
ADD_TEST(ddsc_take_next, reader, true);
ADD_TEST(ddsc_take_next_wl, reader, true);
ADD_TEST(ddsc_read_next, invalid_readers, true);
ADD_TEST(ddsc_read_next, non_readers, true);
ADD_TEST(ddsc_read_next, already_deleted, true);
ADD_TEST(ddsc_read_next, invalid_buffers, true);
ADD_TEST(ddsc_read_next_wl, invalid_readers, true);
ADD_TEST(ddsc_read_next_wl, non_readers, true);
ADD_TEST(ddsc_read_next_wl, already_deleted, true);
ADD_TEST(ddsc_read_next_wl, invalid_buffers, true);
ADD_TEST(ddsc_take_next, invalid_readers, true);
ADD_TEST(ddsc_take_next, non_readers, true);
ADD_TEST(ddsc_take_next, already_deleted, true);
ADD_TEST(ddsc_take_next, invalid_buffers, true);
ADD_TEST(ddsc_take_next_wl, invalid_readers, true);
ADD_TEST(ddsc_take_next_wl, non_readers, true);
ADD_TEST(ddsc_take_next_wl, already_deleted, true);
ADD_TEST(ddsc_take_next_wl, invalid_buffers, true);
ADD_SUITE(ddsc_read_instance, NULL, NULL);
ADD_SUITE(ddsc_read_instance_mask, NULL, NULL);
ADD_SUITE(ddsc_read_instance_mask_wl, NULL, NULL);
ADD_SUITE(ddsc_read_instance_wl, NULL, NULL);
ADD_TEST(ddsc_read_instance, reader, true);
ADD_TEST(ddsc_read_instance_wl, reader, true);
ADD_TEST(ddsc_read_instance_mask, reader, true);
ADD_TEST(ddsc_read_instance_mask_wl, reader, true);
ADD_TEST(ddsc_read_instance, readcondition, true);
ADD_TEST(ddsc_read_instance_wl, readcondition, true);
ADD_TEST(ddsc_read_instance_mask, readcondition, true);
ADD_TEST(ddsc_read_instance_mask_wl, readcondition, true);
ADD_TEST(ddsc_read_instance, querycondition, true);
ADD_TEST(ddsc_read_instance_wl, querycondition, true);
ADD_TEST(ddsc_read_instance_mask, querycondition, true);
ADD_TEST(ddsc_read_instance_mask_wl, querycondition, true);
ADD_TEST(ddsc_read_instance, invalid_params, true);
ADD_TEST(ddsc_read_instance_wl, invalid_params, true);
ADD_TEST(ddsc_read_instance_mask, invalid_params, true);
ADD_TEST(ddsc_read_instance_mask_wl, invalid_params, true);
ADD_TEST(ddsc_read_instance, invalid_handles, true);
ADD_TEST(ddsc_read_instance_wl, invalid_handles, true);
ADD_TEST(ddsc_read_instance_mask, invalid_handles, true);
ADD_TEST(ddsc_read_instance_mask_wl, invalid_handles, true);
ADD_TEST(ddsc_read_instance, invalid_readers, true);
ADD_TEST(ddsc_read_instance_wl, invalid_readers, true);
ADD_TEST(ddsc_read_instance_mask, invalid_readers, true);
ADD_TEST(ddsc_read_instance_mask_wl, invalid_readers, true);
ADD_TEST(ddsc_read_instance, non_readers, true);
ADD_TEST(ddsc_read_instance_wl, non_readers, true);
ADD_TEST(ddsc_read_instance_mask, non_readers, true);
ADD_TEST(ddsc_read_instance_mask_wl, non_readers, true);
ADD_TEST(ddsc_read_instance, already_deleted, true);
ADD_TEST(ddsc_read_instance_wl, already_deleted, true);
ADD_TEST(ddsc_read_instance_mask, already_deleted, true);
ADD_TEST(ddsc_read_instance_mask_wl, already_deleted, true);
ADD_SUITE(ddsc_register_instance, NULL, NULL);
ADD_TEST(ddsc_register_instance, deleted_entity, true);
ADD_TEST(ddsc_register_instance, registering_new_instance, true);
ADD_TEST(ddsc_register_instance, data_already_available, true);
ADD_TEST(ddsc_register_instance, invalid_params, true);
ADD_TEST(ddsc_register_instance, invalid_writers, true);
ADD_TEST(ddsc_register_instance, non_writers, true);
ADD_SUITE(ddsc_subscriber, NULL, NULL);
ADD_TEST(ddsc_subscriber, notify_readers, true);
ADD_TEST(ddsc_subscriber, create, true);
ADD_TEST(ddsc_subscriber, invalid_qos, true);
ADD_SUITE(ddsc_take_instance, NULL, NULL);
ADD_SUITE(ddsc_take_instance_mask, NULL, NULL);
ADD_SUITE(ddsc_take_instance_mask_wl, NULL, NULL);
ADD_SUITE(ddsc_take_instance_wl, NULL, NULL);
ADD_TEST(ddsc_take_instance, reader, true);
ADD_TEST(ddsc_take_instance_wl, reader, true);
ADD_TEST(ddsc_take_instance_mask, reader, true);
ADD_TEST(ddsc_take_instance_mask_wl, reader, true);
ADD_TEST(ddsc_take_instance, readcondition, true);
ADD_TEST(ddsc_take_instance_wl, readcondition, true);
ADD_TEST(ddsc_take_instance_mask, readcondition, true);
ADD_TEST(ddsc_take_instance_mask_wl, readcondition, true);
ADD_TEST(ddsc_take_instance, querycondition, true);
ADD_TEST(ddsc_take_instance_wl, querycondition, true);
ADD_TEST(ddsc_take_instance_mask, querycondition, true);
ADD_TEST(ddsc_take_instance_mask_wl, querycondition, true);
ADD_TEST(ddsc_take_instance, invalid_params, true);
ADD_TEST(ddsc_take_instance_wl, invalid_params, true);
ADD_TEST(ddsc_take_instance_mask, invalid_params, true);
ADD_TEST(ddsc_take_instance_mask_wl, invalid_params, true);
ADD_TEST(ddsc_take_instance, invalid_handles, true);
ADD_TEST(ddsc_take_instance_wl, invalid_handles, true);
ADD_TEST(ddsc_take_instance_mask, invalid_handles, true);
ADD_TEST(ddsc_take_instance_mask_wl, invalid_handles, true);
ADD_TEST(ddsc_take_instance, invalid_readers, true);
ADD_TEST(ddsc_take_instance_wl, invalid_readers, true);
ADD_TEST(ddsc_take_instance_mask, invalid_readers, true);
ADD_TEST(ddsc_take_instance_mask_wl, invalid_readers, true);
ADD_TEST(ddsc_take_instance, non_readers, true);
ADD_TEST(ddsc_take_instance_wl, non_readers, true);
ADD_TEST(ddsc_take_instance_mask, non_readers, true);
ADD_TEST(ddsc_take_instance_mask_wl, non_readers, true);
ADD_TEST(ddsc_take_instance, already_deleted, true);
ADD_TEST(ddsc_take_instance_wl, already_deleted, true);
ADD_TEST(ddsc_take_instance_mask, already_deleted, true);
ADD_TEST(ddsc_take_instance_mask_wl, already_deleted, true);
ADD_SUITE(ddsc_time, NULL, NULL);
ADD_TEST(ddsc_time, request_time, true);
ADD_SUITE(ddsc_topic_create, NULL, NULL);
ADD_SUITE(ddsc_topic_get_name, NULL, NULL);
ADD_SUITE(ddsc_topic_get_type_name, NULL, NULL);
ADD_SUITE(ddsc_topic_set_qos, NULL, NULL);
ADD_TEST(ddsc_topic_create, invalid_qos, true);
ADD_TEST(ddsc_topic_create, non_participants, true);
ADD_TEST(ddsc_topic_create, duplicate, true);
ADD_TEST(ddsc_topic_create, same_name, true);
ADD_TEST(ddsc_topic_create, recreate, true);
ADD_TEST(ddsc_topic_create, desc_null, true);
ADD_TEST(ddsc_topic_get_name, valid, true);
ADD_TEST(ddsc_topic_get_name, too_small, true);
ADD_TEST(ddsc_topic_get_name, non_topic, true);
ADD_TEST(ddsc_topic_get_name, deleted, true);
ADD_TEST(ddsc_topic_get_type_name, valid, true);
ADD_TEST(ddsc_topic_get_type_name, too_small, true);
ADD_TEST(ddsc_topic_get_type_name, non_topic, true);
ADD_TEST(ddsc_topic_get_type_name, deleted, true);
ADD_TEST(ddsc_topic_set_qos, valid, true);
ADD_TEST(ddsc_topic_set_qos, inconsistent, true);
ADD_TEST(ddsc_topic_set_qos, immutable, true);
ADD_TEST(ddsc_topic_create, valid, true);
ADD_TEST(ddsc_topic_create, invalid_names, true);
ADD_TEST(ddsc_topic_get_name, invalid_params, true);
ADD_TEST(ddsc_topic_get_type_name, invalid_params, true);
ADD_SUITE(ddsc_topic_find_local, NULL, NULL);
ADD_TEST(ddsc_topic_find_local, domain, true);
ADD_TEST(ddsc_topic_find_local, domain_delete_reversed, true);
ADD_TEST(ddsc_topic_find_local, domain_delete_pp, true);
ADD_TEST(ddsc_topic_find_local, domain_delete_pp_reversed, true);
ADD_TEST(ddsc_topic_find_local, participant, true);
ADD_TEST(ddsc_topic_find_local, non_participants, true);
ADD_TEST(ddsc_topic_find_local, null, true);
ADD_TEST(ddsc_topic_find_local, unknown, true);
ADD_TEST(ddsc_topic_find_local, deleted, true);
ADD_SUITE(ddsc_transient_local, NULL, NULL);
ADD_TEST(ddsc_transient_local, late_joiner, true);
ADD_SUITE(ddsc_types, NULL, NULL);
ADD_TEST(ddsc_types, long_arraytypekey, true);
ADD_TEST(ddsc_types, longlong_arraytypekey, true);
ADD_TEST(ddsc_types, unsignedshort_arraytypekey, true);
ADD_TEST(ddsc_types, unsignedlong_arraytypekey, true);
ADD_TEST(ddsc_types, unsignedlonglong_arraytypekey, true);
ADD_TEST(ddsc_types, float_arraytypekey, true);
ADD_TEST(ddsc_types, double_arraytypekey, true);
ADD_TEST(ddsc_types, char_arraytypekey, true);
ADD_TEST(ddsc_types, boolean_arraytypekey, true);
ADD_TEST(ddsc_types, octet_arraytypekey, true);
ADD_TEST(ddsc_types, alltypeskey, true);
ADD_SUITE(ddsc_unregister_instance, NULL, NULL);
ADD_SUITE(ddsc_unregister_instance_ih, NULL, NULL);
ADD_SUITE(ddsc_unregister_instance_ih_ts, NULL, NULL);
ADD_SUITE(ddsc_unregister_instance_ts, NULL, NULL);
ADD_TEST(ddsc_unregister_instance, deleted, true);
ADD_TEST(ddsc_unregister_instance, null, true);
ADD_TEST(ddsc_unregister_instance, unregistering_old_instance, true);
ADD_TEST(ddsc_unregister_instance_ts, deleted, true);
ADD_TEST(ddsc_unregister_instance_ts, null, true);
ADD_TEST(ddsc_unregister_instance_ts, unregistering_old_instance, true);
ADD_TEST(ddsc_unregister_instance_ts, unregistering_past_sample, true);
ADD_TEST(ddsc_unregister_instance_ih, deleted, true);
ADD_TEST(ddsc_unregister_instance_ih, unregistering_old_instance, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, deleted, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, unregistering_old_instance, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, unregistering_past_sample, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, unregistering_instance, true);
ADD_TEST(ddsc_unregister_instance, dispose_unregistered_sample, true);
ADD_TEST(ddsc_unregister_instance_ts, dispose_unregistered_sample, true);
ADD_TEST(ddsc_unregister_instance, invalid_writers, true);
ADD_TEST(ddsc_unregister_instance, non_writers, true);
ADD_TEST(ddsc_unregister_instance_ts, invalid_writers, true);
ADD_TEST(ddsc_unregister_instance_ts, non_writers, true);
ADD_TEST(ddsc_unregister_instance_ih, invalid_handles, true);
ADD_TEST(ddsc_unregister_instance_ih, invalid_writers, true);
ADD_TEST(ddsc_unregister_instance_ih, non_writers, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, invalid_handles, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, invalid_writers, true);
ADD_TEST(ddsc_unregister_instance_ih_ts, non_writers, true);
ADD_SUITE(ddsc_unsupported, NULL, NULL);
ADD_TEST(ddsc_unsupported, dds_begin_end_coherent, true);
ADD_TEST(ddsc_unsupported, dds_suspend_resume, true);
ADD_TEST(ddsc_unsupported, dds_get_instance_handle, true);
ADD_TEST(ddsc_unsupported, dds_set_qos, true);
ADD_SUITE(ddsc_userdata, NULL, NULL);
ADD_TEST(ddsc_userdata, participant, true);
ADD_TEST(ddsc_userdata, endpoint, true);
ADD_TEST(ddsc_userdata, group, true);
ADD_TEST(ddsc_userdata, topic, true);
ADD_SUITE(ddsc_waitset_attach, NULL, NULL);
ADD_SUITE(ddsc_waitset_attach_detach, NULL, NULL);
ADD_SUITE(ddsc_waitset_create, NULL, NULL);
ADD_SUITE(ddsc_waitset_delete_attached, NULL, NULL);
ADD_SUITE(ddsc_waitset_detach, NULL, NULL);
ADD_SUITE(ddsc_waitset_get_entities, NULL, NULL);
ADD_SUITE(ddsc_waitset_set_trigger, NULL, NULL);
ADD_SUITE(ddsc_waitset_triggering, NULL, NULL);
ADD_SUITE(ddsc_waitset_wait, NULL, NULL);
ADD_SUITE(ddsc_waitset_wait_until, NULL, NULL);
ADD_TEST(ddsc_waitset_create, second, true);
ADD_TEST(ddsc_waitset_create, deleted_participant, true);
ADD_TEST(ddsc_waitset_create, domain, true);
ADD_TEST(ddsc_waitset_create, cyclonedds, true);
ADD_TEST(ddsc_waitset_attach, deleted_waitset, true);
ADD_TEST(ddsc_waitset_attach_detach, second, true);
ADD_TEST(ddsc_waitset_attach_detach, various, true);
ADD_TEST(ddsc_waitset_attach_detach, combinations, true);
ADD_TEST(ddsc_waitset_delete_attached, self, true);
ADD_TEST(ddsc_waitset_delete_attached, participant, true);
ADD_TEST(ddsc_waitset_delete_attached, reader, true);
ADD_TEST(ddsc_waitset_delete_attached, various, true);
ADD_TEST(ddsc_waitset_set_trigger, deleted_waitset, true);
ADD_TEST(ddsc_waitset_wait, deleted_waitset, true);
ADD_TEST(ddsc_waitset_wait_until, deleted_waitset, true);
ADD_TEST(ddsc_waitset_wait_until, past, true);
ADD_TEST(ddsc_waitset_get_entities, no_array, true);
ADD_TEST(ddsc_waitset_get_entities, deleted_waitset, true);
ADD_TEST(ddsc_waitset_triggering, on_self, true);
ADD_TEST(ddsc_waitset_triggering, on_reader, true);
ADD_TEST(ddsc_waitset_triggering, on_readcondition, true);
ADD_TEST(ddsc_waitset_create, invalid_params, true);
ADD_TEST(ddsc_waitset_create, non_participants, true);
ADD_TEST(ddsc_waitset_attach, invalid_params, true);
ADD_TEST(ddsc_waitset_attach, invalid_waitsets, true);
ADD_TEST(ddsc_waitset_attach, non_waitsets, true);
ADD_TEST(ddsc_waitset_attach, scoping, true);
ADD_TEST(ddsc_waitset_attach_detach, valid_entities, true);
ADD_TEST(ddsc_waitset_detach, invalid_params, true);
ADD_TEST(ddsc_waitset_detach, invalid_waitsets, true);
ADD_TEST(ddsc_waitset_detach, valid_entities, true);
ADD_TEST(ddsc_waitset_set_trigger, invalid_params, true);
ADD_TEST(ddsc_waitset_set_trigger, non_waitsets, true);
ADD_TEST(ddsc_waitset_wait, invalid_waitsets, true);
ADD_TEST(ddsc_waitset_wait, non_waitsets, true);
ADD_TEST(ddsc_waitset_wait, invalid_params, true);
ADD_TEST(ddsc_waitset_wait_until, invalid_waitsets, true);
ADD_TEST(ddsc_waitset_wait_until, non_waitsets, true);
ADD_TEST(ddsc_waitset_wait_until, invalid_params, true);
ADD_TEST(ddsc_waitset_get_entities, array_sizes, true);
ADD_TEST(ddsc_waitset_get_entities, invalid_params, true);
ADD_TEST(ddsc_waitset_get_entities, non_waitsets, true);
ADD_TEST(ddsc_waitset_triggering, after_listener, true);
ADD_SUITE(ddsc_waitset, NULL, NULL);
ADD_TEST(ddsc_waitset, torture, true);
ADD_SUITE(ddsc_whc, NULL, NULL);
ADD_TEST(ddsc_whc, check_end_state, true);
ADD_SUITE(ddsc_write, NULL, NULL);
ADD_SUITE(ddsc_write_ts, NULL, NULL);
ADD_TEST(ddsc_write, basic, true);
ADD_TEST(ddsc_write, null_writer, true);
ADD_TEST(ddsc_write, bad_writer, true);
ADD_TEST(ddsc_write, closed_writer, true);
ADD_TEST(ddsc_write, null_sample, true);
ADD_TEST(ddsc_write_ts, basic, true);
ADD_TEST(ddsc_write_ts, bad_timestamp, true);
ADD_TEST(ddsc_write, simpletypes, true);
ADD_SUITE(ddsc_writetypes, NULL, NULL);
ADD_TEST(ddsc_writetypes, various, true);
ADD_SUITE(ddsc_create_writer, NULL, NULL);
ADD_TEST(ddsc_create_writer, basic, true);
ADD_TEST(ddsc_create_writer, null_parent, true);
ADD_TEST(ddsc_create_writer, bad_parent, true);
ADD_TEST(ddsc_create_writer, participant, true);
ADD_TEST(ddsc_create_writer, wrong_participant, true);
ADD_TEST(ddsc_create_writer, publisher, true);
ADD_TEST(ddsc_create_writer, deleted_publisher, true);
ADD_TEST(ddsc_create_writer, null_topic, true);
ADD_TEST(ddsc_create_writer, bad_topic, true);
ADD_TEST(ddsc_create_writer, deleted_topic, true);
ADD_TEST(ddsc_create_writer, participant_mismatch, true);
ADD_SUITE(ddsc_cdrstream, NULL, NULL);
ADD_TEST(ddsc_cdrstream, ser_des, true);
ADD_TEST(ddsc_cdrstream, ser_des_multiple, true);
ADD_TEST(ddsc_cdrstream, appendable_mutable, true);
ADD_TEST(ddsc_cdrstream, min_xcdr_version, true);
ADD_TEST(ddsc_cdrstream, check_optimize, true);
ADD_SUITE(ddsc_data_representation, NULL, NULL);
ADD_TEST(ddsc_data_representation, xcdr1_xcdr2, true);
ADD_TEST(ddsc_data_representation, matching, true);
ADD_TEST(ddsc_data_representation, extensibility, true);
ADD_TEST(ddsc_data_representation, update_qos, true);
ADD_SUITE(ddsc_lifespan, NULL, NULL);
ADD_TEST(ddsc_lifespan, basic, true);
ADD_SUITE(ddsc_deadline, NULL, NULL);
ADD_TEST(ddsc_deadline, basic, true);
ADD_TEST(ddsc_deadline, writer_types, true);
ADD_TEST(ddsc_deadline, instances, true);

    CU_set_error_action(opts.error_action);

    if (opts.automated) {
        if (opts.results != NULL) {
            CU_set_output_filename(opts.results);
        }

#if defined(HAVE_ENABLE_JUNIT_XML)
        if (opts.junit) {
            CU_automated_enable_junit_xml(CU_TRUE);
        } else
#endif
        {
            CU_list_tests_to_file();
        }
        CU_automated_run_tests();
    } else {
        CU_set_fail_on_inactive(0);
        CU_basic_set_mode(opts.mode);
        CU_basic_run_tests();
    }

    if (CU_get_error() != CUE_SUCCESS) {
        ret = EX_SOFTWARE;
    } else if (CU_get_number_of_failures() != 0) {
        ret = EXIT_FAILURE;
    }

    CU_cleanup_registry();

    return ret;
}

