/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RoundTrip.c
  Source: RoundTrip.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "RoundTrip.h"

static const uint32_t RoundTripModule_DataType_ops [] =
{
  /* DataType */
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (RoundTripModule_DataType, payload),
  DDS_OP_RTS
};

const dds_topic_descriptor_t RoundTripModule_DataType_desc =
{
  .m_size = sizeof (RoundTripModule_DataType),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 0u,
  .m_typename = "RoundTripModule::DataType",
  .m_keys = NULL,
  .m_nops = 2,
  .m_ops = RoundTripModule_DataType_ops,
  .m_meta = ""
};

static const uint32_t RoundTripModule_Address_ops [] =
{
  /* Address */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (RoundTripModule_Address, ip),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (RoundTripModule_Address, port),
  DDS_OP_RTS,
  
  /* key: ip */
  DDS_OP_KOF | 1, 0u /* order: 0 */,
  
  /* key: port */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t RoundTripModule_Address_keys[2] =
{
  { "ip", 5, 0 },
  { "port", 7, 1 }
};

const dds_topic_descriptor_t RoundTripModule_Address_desc =
{
  .m_size = sizeof (RoundTripModule_Address),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 2u,
  .m_typename = "RoundTripModule::Address",
  .m_keys = RoundTripModule_Address_keys,
  .m_nops = 3,
  .m_ops = RoundTripModule_Address_ops,
  .m_meta = ""
};

