/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: Space.c
  Source: Space.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "Space.h"

static const uint32_t Space_Type1_ops [] =
{
  /* Type1 */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type1, long_1),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type1, long_2),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type1, long_3),
  DDS_OP_RTS,
  
  /* key: long_1 */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t Space_Type1_keys[1] =
{
  { "long_1", 7, 0 }
};

const dds_topic_descriptor_t Space_Type1_desc =
{
  .m_size = sizeof (Space_Type1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "Space::Type1",
  .m_keys = Space_Type1_keys,
  .m_nops = 4,
  .m_ops = Space_Type1_ops,
  .m_meta = ""
};

static const uint32_t Space_Type2_ops [] =
{
  /* Type2 */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type2, long_1),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type2, long_2),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type2, long_3),
  DDS_OP_RTS,
  
  /* key: long_1 */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t Space_Type2_keys[1] =
{
  { "long_1", 7, 0 }
};

const dds_topic_descriptor_t Space_Type2_desc =
{
  .m_size = sizeof (Space_Type2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "Space::Type2",
  .m_keys = Space_Type2_keys,
  .m_nops = 4,
  .m_ops = Space_Type2_ops,
  .m_meta = ""
};

static const uint32_t Space_Type3_ops [] =
{
  /* Type3 */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type3, long_1),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type3, long_2),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_Type3, long_3),
  DDS_OP_RTS
};

const dds_topic_descriptor_t Space_Type3_desc =
{
  .m_size = sizeof (Space_Type3),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "Space::Type3",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = Space_Type3_ops,
  .m_meta = ""
};

static const uint32_t Space_simpletypes_ops [] =
{
  /* simpletypes */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (Space_simpletypes, l),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (Space_simpletypes, ll),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (Space_simpletypes, us),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Space_simpletypes, ul),
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (Space_simpletypes, ull),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (Space_simpletypes, f),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (Space_simpletypes, d),
  DDS_OP_ADR | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (Space_simpletypes, c),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (Space_simpletypes, b),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (Space_simpletypes, o),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (Space_simpletypes, s),
  DDS_OP_RTS,
  
  /* key: s */
  DDS_OP_KOF | 1, 20u /* order: 10 */
};

static const dds_key_descriptor_t Space_simpletypes_keys[1] =
{
  { "s", 23, 0 }
};

const dds_topic_descriptor_t Space_simpletypes_desc =
{
  .m_size = sizeof (Space_simpletypes),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 1u,
  .m_typename = "Space::simpletypes",
  .m_keys = Space_simpletypes_keys,
  .m_nops = 12,
  .m_ops = Space_simpletypes_ops,
  .m_meta = ""
};

