/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: TypesArrayKey.c
  Source: TypesArrayKey.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "TypesArrayKey.h"

static const uint32_t TypesArrayKey_long_arraytypekey_ops [] =
{
  /* long_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_long_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_long_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_long_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_long_arraytypekey),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::long_arraytypekey",
  .m_keys = TypesArrayKey_long_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_long_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_longlong_arraytypekey_ops [] =
{
  /* longlong_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_longlong_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_longlong_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_longlong_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_longlong_arraytypekey),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::longlong_arraytypekey",
  .m_keys = TypesArrayKey_longlong_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_longlong_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_unsignedshort_arraytypekey_ops [] =
{
  /* unsignedshort_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (TypesArrayKey_unsignedshort_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_unsignedshort_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_unsignedshort_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_unsignedshort_arraytypekey),
  .m_align = 2u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::unsignedshort_arraytypekey",
  .m_keys = TypesArrayKey_unsignedshort_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_unsignedshort_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_unsignedlong_arraytypekey_ops [] =
{
  /* unsignedlong_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (TypesArrayKey_unsignedlong_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_unsignedlong_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_unsignedlong_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_unsignedlong_arraytypekey),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::unsignedlong_arraytypekey",
  .m_keys = TypesArrayKey_unsignedlong_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_unsignedlong_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_unsignedlonglong_arraytypekey_ops [] =
{
  /* unsignedlonglong_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY, offsetof (TypesArrayKey_unsignedlonglong_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_unsignedlonglong_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_unsignedlonglong_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_unsignedlonglong_arraytypekey),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::unsignedlonglong_arraytypekey",
  .m_keys = TypesArrayKey_unsignedlonglong_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_unsignedlonglong_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_float_arraytypekey_ops [] =
{
  /* float_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (TypesArrayKey_float_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_float_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_float_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_float_arraytypekey),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::float_arraytypekey",
  .m_keys = TypesArrayKey_float_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_float_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_double_arraytypekey_ops [] =
{
  /* double_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY | DDS_OP_FLAG_FP, offsetof (TypesArrayKey_double_arraytypekey, key), 20u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_double_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_double_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_double_arraytypekey),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::double_arraytypekey",
  .m_keys = TypesArrayKey_double_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_double_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_char_arraytypekey_ops [] =
{
  /* char_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_char_arraytypekey, key), 128u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_char_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_char_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_char_arraytypekey),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::char_arraytypekey",
  .m_keys = TypesArrayKey_char_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_char_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_boolean_arraytypekey_ops [] =
{
  /* boolean_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (TypesArrayKey_boolean_arraytypekey, key), 128u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_boolean_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_boolean_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_boolean_arraytypekey),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::boolean_arraytypekey",
  .m_keys = TypesArrayKey_boolean_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_boolean_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_octet_arraytypekey_ops [] =
{
  /* octet_arraytypekey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (TypesArrayKey_octet_arraytypekey, key), 128u,
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t TypesArrayKey_octet_arraytypekey_keys[1] =
{
  { "key", 4, 0 }
};

const dds_topic_descriptor_t TypesArrayKey_octet_arraytypekey_desc =
{
  .m_size = sizeof (TypesArrayKey_octet_arraytypekey),
  .m_align = 1u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "TypesArrayKey::octet_arraytypekey",
  .m_keys = TypesArrayKey_octet_arraytypekey_keys,
  .m_nops = 2,
  .m_ops = TypesArrayKey_octet_arraytypekey_ops,
  .m_meta = ""
};

static const uint32_t TypesArrayKey_alltypeskey_ops [] =
{
  /* alltypeskey */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_alltypeskey, l),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_8BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_alltypeskey, ll),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_2BY, offsetof (TypesArrayKey_alltypeskey, us),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY, offsetof (TypesArrayKey_alltypeskey, ul),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_8BY, offsetof (TypesArrayKey_alltypeskey, ull),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (TypesArrayKey_alltypeskey, f),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (TypesArrayKey_alltypeskey, d),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_1BY | DDS_OP_FLAG_SGN, offsetof (TypesArrayKey_alltypeskey, c),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_1BY, offsetof (TypesArrayKey_alltypeskey, b),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_1BY, offsetof (TypesArrayKey_alltypeskey, o),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (TypesArrayKey_alltypeskey, s),
  DDS_OP_RTS,
  
  /* key: l */
  DDS_OP_KOF | 1, 0u /* order: 0 */,
  
  /* key: ll */
  DDS_OP_KOF | 1, 2u /* order: 1 */,
  
  /* key: us */
  DDS_OP_KOF | 1, 4u /* order: 2 */,
  
  /* key: ul */
  DDS_OP_KOF | 1, 6u /* order: 3 */,
  
  /* key: ull */
  DDS_OP_KOF | 1, 8u /* order: 4 */,
  
  /* key: f */
  DDS_OP_KOF | 1, 10u /* order: 5 */,
  
  /* key: d */
  DDS_OP_KOF | 1, 12u /* order: 6 */,
  
  /* key: c */
  DDS_OP_KOF | 1, 14u /* order: 7 */,
  
  /* key: b */
  DDS_OP_KOF | 1, 16u /* order: 8 */,
  
  /* key: o */
  DDS_OP_KOF | 1, 18u /* order: 9 */,
  
  /* key: s */
  DDS_OP_KOF | 1, 20u /* order: 10 */
};

static const dds_key_descriptor_t TypesArrayKey_alltypeskey_keys[11] =
{
  { "l", 23, 0 },
  { "ll", 25, 1 },
  { "us", 27, 2 },
  { "ul", 29, 3 },
  { "ull", 31, 4 },
  { "f", 33, 5 },
  { "d", 35, 6 },
  { "c", 37, 7 },
  { "b", 39, 8 },
  { "o", 41, 9 },
  { "s", 43, 10 }
};

const dds_topic_descriptor_t TypesArrayKey_alltypeskey_desc =
{
  .m_size = sizeof (TypesArrayKey_alltypeskey),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE,
  .m_nkeys = 11u,
  .m_typename = "TypesArrayKey::alltypeskey",
  .m_keys = TypesArrayKey_alltypeskey_keys,
  .m_nops = 12,
  .m_ops = TypesArrayKey_alltypeskey_ops,
  .m_meta = ""
};

