/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: WriteTypes.c
  Source: WriteTypes.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "WriteTypes.h"

static const uint32_t WriteTypes_a_ops [] =
{
  /* a */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (WriteTypes_a, k), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (WriteTypes_a, ll),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t WriteTypes_a_keys[1] =
{
  { "k", 6, 0 }
};

const dds_topic_descriptor_t WriteTypes_a_desc =
{
  .m_size = sizeof (WriteTypes_a),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "WriteTypes::a",
  .m_keys = WriteTypes_a_keys,
  .m_nops = 3,
  .m_ops = WriteTypes_a_ops,
  .m_meta = ""
};

static const uint32_t WriteTypes_b_ops [] =
{
  /* b */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (WriteTypes_b, k), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (WriteTypes_b, ll),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t WriteTypes_b_keys[1] =
{
  { "k", 6, 0 }
};

const dds_topic_descriptor_t WriteTypes_b_desc =
{
  .m_size = sizeof (WriteTypes_b),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "WriteTypes::b",
  .m_keys = WriteTypes_b_keys,
  .m_nops = 3,
  .m_ops = WriteTypes_b_ops,
  .m_meta = ""
};

static const uint32_t WriteTypes_c_ops [] =
{
  /* c */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (WriteTypes_c, k), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (WriteTypes_c, ll),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t WriteTypes_c_keys[1] =
{
  { "k", 6, 0 }
};

const dds_topic_descriptor_t WriteTypes_c_desc =
{
  .m_size = sizeof (WriteTypes_c),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_KEY | DDS_TOPIC_FIXED_KEY_XCDR2 | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "WriteTypes::c",
  .m_keys = WriteTypes_c_keys,
  .m_nops = 3,
  .m_ops = WriteTypes_c_ops,
  .m_meta = ""
};

static const uint32_t WriteTypes_d_ops [] =
{
  /* d */
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_8BY, offsetof (WriteTypes_d, k), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (WriteTypes_d, ll),
  DDS_OP_RTS,
  
  /* key: k */
  DDS_OP_KOF | 1, 0u /* order: 0 */
};

static const dds_key_descriptor_t WriteTypes_d_keys[1] =
{
  { "k", 6, 0 }
};

const dds_topic_descriptor_t WriteTypes_d_desc =
{
  .m_size = sizeof (WriteTypes_d),
  .m_align = 8u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 1u,
  .m_typename = "WriteTypes::d",
  .m_keys = WriteTypes_d_keys,
  .m_nops = 3,
  .m_ops = WriteTypes_d_ops,
  .m_meta = ""
};

