/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: XSpaceMustUnderstand.c
  Source: XSpaceMustUnderstand.idl
  Cyclone DDS: V0.9.0

*****************************************************************/
#include "XSpaceMustUnderstand.h"

static const uint32_t XSpaceMustUnderstand_rd1_ops [] =
{
  /* rd1 */
  DDS_OP_PLC,
  DDS_OP_PLM | 3, 0u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_rd1, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_rd1_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_rd1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::rd1",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = XSpaceMustUnderstand_rd1_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_wr1_1_ops [] =
{
  /* wr1_1 */
  DDS_OP_PLC,
  DDS_OP_PLM | 5, 0u,
  DDS_OP_PLM | 6, 1u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_1, f1),
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_1, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_1_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_wr1_1),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::wr1_1",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = XSpaceMustUnderstand_wr1_1_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_wr1_2_ops [] =
{
  /* wr1_2 */
  DDS_OP_PLC,
  DDS_OP_PLM | 3, 0u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_FLAG_MU | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_2, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_2_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_wr1_2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::wr1_2",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = XSpaceMustUnderstand_wr1_2_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_wr1_3_ops [] =
{
  /* wr1_3 */
  DDS_OP_PLC,
  DDS_OP_PLM | 5, 0u,
  DDS_OP_PLM | 6, 1u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_3, f1),
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_FLAG_MU | DDS_OP_FLAG_OPT | DDS_OP_FLAG_EXT | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_3, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_3_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_wr1_3),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::wr1_3",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = XSpaceMustUnderstand_wr1_3_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_wr1_4_ops [] =
{
  /* wr1_4 */
  DDS_OP_PLC,
  DDS_OP_PLM | 3, 0u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_FLAG_MU | DDS_OP_FLAG_OPT | DDS_OP_FLAG_EXT | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_wr1_4, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_wr1_4_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_wr1_4),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::wr1_4",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = XSpaceMustUnderstand_wr1_4_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_rd2_ops [] =
{
  /* rd2 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (XSpaceMustUnderstand_rd2, f1), (3u << 16u) + 4u /* n2 */,
  DDS_OP_RTS,

  /* n2 */
  DDS_OP_PLC,
  DDS_OP_PLM | 3, 0u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_n2, f1),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_rd2_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_rd2),
  .m_align = 4u,
  .m_flagset = DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::rd2",
  .m_keys = NULL,
  .m_nops = 6,
  .m_ops = XSpaceMustUnderstand_rd2_ops,
  .m_meta = ""
};

static const uint32_t XSpaceMustUnderstand_wr2_1_ops [] =
{
  /* wr2_1 */
  DDS_OP_ADR | DDS_OP_TYPE_EXT, offsetof (XSpaceMustUnderstand_wr2_1, f1), (3u << 16u) + 4u /* n2_mu */,
  DDS_OP_RTS,

  /* n2_mu */
  DDS_OP_PLC,
  DDS_OP_PLM | 5, 0u,
  DDS_OP_PLM | 6, 1u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_n2_mu, f1),
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_FLAG_MU | DDS_OP_FLAG_OPT | DDS_OP_FLAG_EXT | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (XSpaceMustUnderstand_n2_mu, f2),
  DDS_OP_RTS
};

const dds_topic_descriptor_t XSpaceMustUnderstand_wr2_1_desc =
{
  .m_size = sizeof (XSpaceMustUnderstand_wr2_1),
  .m_align = sizeof (char *),
  .m_flagset = DDS_TOPIC_NO_OPTIMIZE | DDS_TOPIC_FIXED_SIZE,
  .m_nkeys = 0u,
  .m_typename = "XSpaceMustUnderstand::wr2_1",
  .m_keys = NULL,
  .m_nops = 8,
  .m_ops = XSpaceMustUnderstand_wr2_1_ops,
  .m_meta = ""
};

